(function(g){var window=this;'use strict';var OA=function(y){y.isActive()||y.start()},lh=function(y){var X={languageCode:y.languageCode,
languageName:y.languageName,displayName:g.AB(y),kind:y.kind,name:y.name,id:y.id,is_servable:y.B,is_default:y.isDefault,is_translateable:y.isTranslateable,vss_id:y.vssId};y.xtags&&(X.xtags=y.xtags);y.captionId&&(X.captionId=y.captionId);y.translationLanguage&&(X.translationLanguage=y.translationLanguage);return X},Bwj=function(y,X){var n=new g.k$;
n.languageCode=y.languageCode;n.languageName=y.languageName;n.name=y.name;n.displayName=y.displayName;n.kind=y.kind;n.isDefault=!1;n.B=y.B;n.isTranslateable=y.isTranslateable;n.vssId=y.vssId;n.url=y.url;n.translationLanguage=X;y.xtags&&(n.xtags=y.xtags);y.captionId&&(n.captionId=y.captionId);return n},UA=function(y,X){return X?y.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},pcL=function(y){return g.Gv(y)||y.j("web_enable_caption_language_preference_stickiness")},$t0=async function(y,X){y=
y+"|"+X;
X=await g.Sn();if(!X)throw g.vg("gct");return(await g.D0(X)).get("captions",y)},f8j=function(y,X,n){$t0(y,X).then(B=>{B&&n(B.trackData,new g.k$(B.metadata))})},VV=function(y){if(!GpA.test(y))throw Error("'"+y+"' is not a valid hex color");
y.length==4&&(y=y.replace(v6V,"#$1$1$2$2$3$3"));y=y.toLowerCase();y=parseInt(y.slice(1),16);return[y>>16,y>>8&255,y&255]},Nwm=function(){var y={},X="suggest_correction"in g.Vl?g.Vl.suggest_correction:"Edit caption";
X=X||"";for(let n in y){let B=()=>String(y[n]);
X=X.replace(new RegExp("\\$\\{"+n+"\\}","gi"),B);X=X.replace(new RegExp("\\$"+n,"gi"),B)}return X},LN=function(){return g.Oi("yt-player-caption-display-settings")},Dtj=function(y,X){g.te(X,n=>y.equals(n))||X.push(y)},EA=function(y,X){switch(X.kind){case "asr":Dtj(X,y.Z);
break;default:Dtj(X,y.D)}},o61=async function(y,X,n){y.D=g.FT(X,n)},TwG=function(y,X){var n=g.X_(y.segments,X);
n>=0||n<0&&(-n-1)%2===1||(n=-n-1,n>0&&X-y.segments[n-1]===1&&n<y.segments.length&&y.segments[n]-X===1?(g.w1(y.segments,n),g.w1(y.segments,n-1)):n>0&&X-y.segments[n-1]===1?y.segments[n-1]=X:n<y.segments.length&&y.segments[n]-X===1?y.segments[n]=X:(g.qh(y.segments,n,0,X),g.qh(y.segments,n+1,0,X)))},ZlH=function(y){return y.B&&y.B.V?y.B.V+y.player.JA()<y.player.getCurrentTime():!1},ilH=function(y,X){if(y.policy.f1&&y.player.F7()){var n=g.bc(X,y.policy,{});
n.set("pot",y.player.F7());n=n.KZ()}else n=g.bc(X,y.policy,{}).KZ();var B={format:"RAW",withCredentials:!0};if(y.policy.Fa){B.method="POST";let G=X.W;G&&Object.keys(G).length>0?B.postBody=g.Q3(G,g.dV):B.postBody=(0,g.T2)([120,0])}y.V&&(B.responseType="arraybuffer");var p=++y.Z$,f=(0,g.C)();y.D=g.fR(n,B,3,100,-1,G=>{G.errorCode==="net.timeout"&&y.player.O("capnt",{rn:p++})}).then(G=>{if(y.policy.Ve&&p%100===1){var v=(0,g.C)();
y.player.O("caprsp",{rn:p,ms:v-f,kb:(G.xhr.responseText.length/1024).toFixed()})}a:{G=G.xhr;y.Vo();if(y.Z){var N=!(y.V?G.response:G.responseText)||G.status>=400;if(v=g.wo(G)){G=g.bc(y.Z,y.policy,{});y.Z.aB(G,v);ilH(y,y.Z);break a}N?y.player.O("capfail",{status:G.status}):(g.cP("fcb_r",(0,g.C)(),y.player.getVideoData()?.YM||""),v=y.Z.Mt[0],N=v.zs,y.A!=null&&y.C!==N&&(y.V?y.A(G.response,(v.segmentStartTime+y.player.JA())*1E3):y.A(G.responseText,(v.segmentStartTime+y.player.JA())*1E3),y.C=N))}y.Z=null;
y.D=null}}).i7(G=>{y.Z=null;
y.D=null;y.player.O("capfail",{rn:p,status:G.xhr?.status})});
y.Z=X;TwG(y.W,y.Z.Mt[0].zs)},JpL=function(y,X){return X!=null&&X in y.D.B?y.D.B[X]:null},blb=function(y,X,n){var B=[];
for(let p in y.D.B){if(!y.D.B.hasOwnProperty(p))continue;let f=y.D.B[p];if(g.MP(f,n||null)){let G=f.info.captionTrack;G&&G.languageCode===X&&B.push(f)}}return B.length?B[0]:null},Ol0=function(y,X){var n=[];
for(let p in y.D.B){if(!y.D.B.hasOwnProperty(p))continue;var B=y.D.B[p];if(g.MP(B,X||null)){let f=B.info.id,G=f,v=`.${f}`,N="",J="";if(B=B.info.captionTrack)f=B.languageCode,G=B.displayName,v=B.vssId,N=B.kind,J=B.id;n.push(new g.k$({id:p,languageCode:f,languageName:G,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:v,kind:N,captionId:J}))}}return n},sA=function(y){if(typeof DOMParser!="undefined")return g.Dh(new DOMParser,g.NR(y),"application/xml");
throw Error("Your browser does not support loading xml documents");},l8c=function(y,X,n,B){var p=X/360*16;
X>=y&&(y=640,B>n*1.3&&(y=480),p=n/y*16);return p},Ut0=function(y){var X=1+.25*(y.fontSizeIncrement||0);
if(y.offset===0||y.offset===2)X*=.8;return X},VTj=function(y,X){var n="vertical-rl";
y.B.oC===1&&(n="vertical-lr");g.wF&&(n=n==="vertical-lr"?"tb-lr":"tb-rl");g.nq(X,"-o-writing-mode",n);g.nq(X,"-webkit-writing-mode",n);g.nq(X,"writing-mode",n);g.nq(X,"text-orientation","upright");g.sK(X,"ytp-vertical-caption");y.Z.params.V6===3&&(g.nq(X,"text-orientation",""),g.nq(X,"transform","rotate(180deg)"))},L9s=function(y,X){var n={},B=X.background?X.background:y.B.Qw.background;
if(X.backgroundOpacity!=null||X.background){var p=X.backgroundOpacity!=null?X.backgroundOpacity:y.B.Qw.backgroundOpacity;B=VV(B);n.background="rgba("+B[0]+","+B[1]+","+B[2]+","+p+")";y.hw&&(n["box-decoration-break"]="clone",n["border-radius"]=`${y.l0*.25}px`)}if(X.fontSizeIncrement!=null||X.offset!=null)n["font-size"]=`${y.Qo*Ut0(X)}px`;y.experiments.Nt("enable_player_captions_new_style_defaults")&&(n["line-height"]="1.375");B=1;p=X.color||y.B.Qw.color;if(X.color||X.textOpacity!=null)p=VV(p),B=X.textOpacity==
null?y.B.Qw.textOpacity:X.textOpacity,p="rgba("+p[0]+","+p[1]+","+p[2]+","+B+")",n.color=p,n.fill=p;var f=X.charEdgeStyle;f===0&&(f=void 0);if(f){p=`rgba(34, 34, 34, ${B})`;let N=`rgba(204, 204, 204, ${B})`;X.lr&&(N=p=X.lr);let J=y.Qo/16/2,b=Math.max(J,1);var G=Math.max(2*J,1),v=Math.max(3*J,1);let l=Math.max(5*J,1);B=[];switch(f){case 4:for(;v<=l;v+=J)B.push(`${G}px ${G}px ${v}px ${p}`);break;case 1:G=window.devicePixelRatio>=2?.5:1;for(f=b;f<=v;f+=G)B.push(`${f}px ${f}px ${p}`);break;case 2:B.push(`${b}px ${b}px ${N}`);
B.push(`-${b}px -${b}px ${p}`);break;case 3:for(v=0;v<5;v++)B.push(`0 0 ${G}px ${p}`)}n["text-shadow"]=B.join(", ")}p="";switch(X.fontFamily){case 1:p='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:p='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:p='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:p='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:p='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:p=g.cT()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:p='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}p&&(n["font-family"]=p);p=X.offset;p==null&&(p=y.B.Qw.offset);switch(p){case 0:n["vertical-align"]="sub";break;case 2:n["vertical-align"]="super"}X.fontFamily===7&&(n["font-variant"]="small-caps");X.bold&&(n["font-weight"]="bold");X.italic&&(n["font-style"]="italic");X.underline&&
(n["text-decoration"]="underline");X.jD&&(n.visibility="hidden");X.dJ===1&&y.C&&(n["text-combine-upright"]="all",n["text-orientation"]="mixed",p=g.i3||g.$5,y.Z.params.V6===3?n.transform=p?"rotate(90deg)":"rotate(180deg)":p&&(n.transform="rotate(-90deg)"));if(X.textEmphasis===1||X.textEmphasis===2||X.textEmphasis===3||X.textEmphasis===4||X.textEmphasis===5)if(g.i3)n["font-weight"]="bold";else switch(n["text-emphasis-style"]="filled circle",n["text-emphasis-color"]="currentcolor",n["webkit-text-emphasis"]=
"filled circle",X.textEmphasis){case 4:case 3:n["text-emphasis-position"]="under left";n["webkit-text-emphasis-position"]="under left";break;case 5:case 2:n["text-emphasis-position"]="over right",n["webkit-text-emphasis-position"]="over right"}return n},E6H=function(y,X){if(y.Bd&&X.length===0)return 0;
y=1;for(let n=0;n<X.length;n++){let B=X[n];typeof B.text==="string"&&(y+=B.text.split("\n").length-1,B.append||n===0||y++)}return y},c_=function(y){y=y.split("px");
return y.length>0?(y=Number(y[0]))?y:0:0},W9b=function(y,X,n){y.YL=y.YL||!!n;
var B={};Object.assign(B,y.B.Qw);Object.assign(B,n||X.B);Object.assign(B,y.vZ.Qw);(n=!y.S)&&snj(y);var p=y.kL&&y.Hb&&g.Gw(B,y.Hb)?y.kL:cpc(y,B),f=typeof X.text==="string",G=f?X.text.split("\n"):[X.text];for(let N=0;N<G.length;N++){var v=N>0||!X.append;let J=G[N];v&&!n?(snj(y),p=cpc(y,B)):v&&n&&(n=!1);J&&(p.appendChild(f?g.uw(J):J),f||J.tagName!=="RUBY"||J.childElementCount!==4||g.i3||!g.$X(J.children[2],"text-emphasis")||(v=y.C?"padding-right":"padding-top",g.$X(J.children[2],"text-emphasis-position")&&
(v=y.C?"padding-left":"padding-bottom"),g.cN?g.nq(p,v,"1em"):g.nq(p,v,"0.5em")))}y.Hb=B;y.kL=p;y.U.push(X)},snj=function(y){if(y.S){var X=y.S;
if(y.hw){var n=y.B.textAlign;n===0?(X=X.firstElementChild)&&g.nq(X,{"border-bottom-left-radius":"0"}):n===1&&(X=X.lastElementChild)&&g.nq(X,{"border-bottom-right-radius":"0"})}}y.S=g.PN("SPAN");g.nq(y.S,{display:"block"});g.sK(y.S,"caption-visual-line");y.V.appendChild(y.S)},cpc=function(y,X){var n=g.PN("SPAN");
g.nq(n,{display:"inline-block","white-space":"pre-wrap"});g.nq(n,L9s(y,X));n.classList.add("ytp-caption-segment");y.S.appendChild(n);y.hw&&y.V.children.length>1&&(y=y.B.textAlign,y===0?n.previousElementSibling||g.nq(n,{"border-top-left-radius":"0"}):y===1&&g.nq(n,{"border-top-right-radius":"0"}));n.previousElementSibling&&(g.nq(n.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.nq(n,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return n},
zRI=function(y,X,n){if(y===255&&X===255||!y&&!X)return{Ut:y,
QC:X,result:0};y=Hlj[y];X=Hlj[X];if(y&128){var B;if(B=!(X&128))B=X,B=n.C2()&&n.QC===B;if(B)return{Ut:y,QC:X,result:1}}else if(X&128&&1<=y&&y<=31)return{Ut:y,QC:X,result:2};return{Ut:y,QC:X,result:3}},xt0=function(y,X,n,B){X===255&&n===255||!X&&!n?(++y.Z===45&&y.reset(),y.W.D.clear(),y.V.D.clear()):(y.Z=0,RRL(y.W,X,n,B))},P9L=function(y,X){y.B.sort((n,B)=>{var p=n.time-B.time;
return p===0?n.order-B.order:p});
for(let n of y.B)y.time=n.time,n.type===0?xt0(y,n.CQ,n.Fi,X):n.type===1&&y.D&496&&RRL(y.V,n.CQ,n.Fi,X);y.B.length=0},MTs=function(y,X){switch(y){case 0:return uFI[(X&127)-32];
case 1:return Qn7[X&15];case 2:return K9L[X&31];case 3:return rpc[X&31]}return 0},W_=function(y,X){if(y.style.type===3){var n=0,B=0,p=y.V.time+0,f="",G="",v=p;
for(var N=1;N<=15;++N){var J=!1;for(var b=B?B:1;b<=32;++b){var l=y.Z[N][b];if(l.B!==0){n===0&&(n=N,B=b);J=String.fromCharCode(l.B);var L=l.timestamp;L<p&&(p=L);l.timestamp=v;G&&(f+=G,G="");f+=J;J=!0}if((l.B===0||b===32)&&J){G="\n";break}else if(B&&!J)break}if(n&&!J)break}f&&X.W(n,B,p,v,f)}else for(B=n=0,f=p=y.V.time+0,G=1;G<=15;++G)for(v="",N=1;N<=32;++N)if(b=y.Z[G][N],l=b.B,l!==0&&(n===0&&(n=G,B=N),J=String.fromCharCode(l),L=b.timestamp,L<=p&&(p=L),v+=J,b.reset()),N===32||l===0)v&&X.W(n,B,p,f,v),
p=f,v="",B=n=0},H_=function(y){return y.Z[y.row][y.D]},z5=function(y,X,n){X>=2&&y.D>1&&(--y.D,H_(y).B=0);
var B=H_(y);B.timestamp=y.V.time+0;B.B=MTs(X,n);y.D<32&&y.D++},mts=function(y,X,n,B){for(let G=0;G<B;G++)for(let v=0;v<=32;v++){var p=y.Z[X+G][v],f=y.Z[n+G][v];
p.B=f.B;p.timestamp=f.timestamp}},RB=function(y,X,n){for(let B=0;B<n;B++)for(let p=0;p<=32;p++)y.Z[X+B][p].reset()},x_=function(y){y.row=y.B>0?y.B:1;
y.D=1;RB(y,0,15)},eRb=function(y){y.style.set(1);
y.B=y.W;y.B.B=0;y.B.style=y.style;y.Z.mode=1<<y.B.W},P_=function(y,X,n){var B=y.D,p=!1;
switch(y.style.get()){case 4:case 1:case 2:y.style.get()===4&&B.B>0||(W_(B,n),x_(y.D),x_(y.W),B.row=15,B.B=X,p=!0)}y.style.set(3);y.B=B;y.B.style=y.style;y.Z.mode=1<<B.W;p?B.D=1:B.B!==X&&(B.B>X?(W_(B,n),RB(B,B.row-B.B,X)):B.row<X&&(X=B.B),B.B=X)},tT1=function(y){y.style.set(4);
y.B=y.text;y.B.style=y.style;y.Z.mode=1<<y.B.W},RRL=function(y,X,n,B){y.D.update();
X=zRI(X,n,y.D);switch(X.result){case 0:return;case 1:case 2:return}var p=X.Ut;X=X.QC;if(32<=p||!p)y.B.mode&y.B.D&&(n=p,n&128&&(n=127),X&128&&(X=127),y=y.W.B,n&96&&z5(y,0,n),X&96&&z5(y,0,X),n!==0&&X!==0&&y.style.type===3&&W_(y,B));else if(p&16)a:if(!y.D.matches(p,X)&&(n=y.D,n.Ut=p,n.QC=X,n.state=2,n=p&8?y.C:y.Z,y.W=n,y.B.mode=1<<(y.V<<2)+(n.V<<1)+(n.style.type===4?1:0),(y.B.mode|1<<(y.V<<2)+(n.V<<1)+(n.style.type!==4?1:0))&y.B.D))if(X&64){B=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(p&7)<<1|X>>5&1];
y=X&16?((X&14)>>1)*4:0;X=n.B;switch(n.style.get()){case 4:B=X.row;break;case 3:if(B!==X.row){if(B<X.B&&(B=X.B,B===X.row))break;var f=1+X.row-X.B;let G=1+B-X.B;mts(X,G,f,X.B);n=f;p=X.B;G<f?(f=G+p-f,f>0&&(n+=f,p-=f)):(f=f+p-G,f>0&&(p-=f));RB(X,n,p)}}X.row=B;X.D=y+1}else switch(p&7){case 1:switch(X&112){case 32:z5(n.B,0,32);break a;case 48:X===57?(B=n.B,H_(B).B=0,B.D<32&&B.D++):z5(n.B,1,X&15)}break;case 2:X&32&&z5(n.B,2,X&31);break;case 3:X&32&&z5(n.B,3,X&31);break;case 4:case 5:if(32<=X&&X<=47)switch(X){case 32:eRb(n);
break;case 33:B=n.B;B.D>1&&(--B.D,H_(B).B=0);break;case 36:B=n.B;y=H_(B);for(X=0;X<=15;X++)for(n=0;n<=32;n++)if(B.Z[X][n]===y){for(;n<=32;n++)B.Z[X][n].reset();break}break;case 37:P_(n,2,B);break;case 38:P_(n,3,B);break;case 39:P_(n,4,B);break;case 40:z5(n.B,0,32);break;case 41:B=n;B.style.set(2);B.B=B.D;B.B.B=0;B.B.style=B.style;B.Z.mode=1<<B.B.W;break;case 42:B=n;y=B.text;y.B=15;y.style.set(4);x_(y);tT1(B);break;case 43:tT1(n);break;case 44:y=n;X=y.D;switch(y.style.get()){case 1:case 2:case 3:W_(X,
B)}RB(X,0,15);break;case 45:b:{X=n;y=X.B;switch(X.style.get()){default:case 2:case 1:break b;case 4:if(y.row<15){++y.row;y.D=1;break b}break;case 3:}y.B<2&&(y.B=2,y.row<y.B&&(y.row=y.B));X=y.row-y.B+1;W_(y,B);mts(y,X,X+1,y.B-1);RB(y,y.row,1)}break;case 46:RB(n.W,0,15);break;case 47:y=n,W_(y.D,B),y.W.updateTime(y.Z.time+0),B=y.W,y.W=y.D,y.D=B,eRb(y)}break;case 7:switch(X){case 33:case 34:case 35:B=n.B,(B.D+=X&3)>32&&(B.D=32)}}},kpG=function(y,X,n,B,p,f,G){var v=f[0],N=G[v.getAttribute("p")];
if(N.m9===1){var J=f[1],b=f[2];f=f[3];v.getAttribute("t");J.getAttribute("t");b.getAttribute("t");f.getAttribute("t");v.getAttribute("p");J.getAttribute("p");f.getAttribute("p");G=G[b.getAttribute("p")];v=I8m(v.textContent,J.textContent,b.textContent,f.textContent,G);return new uh(y,X,p,n,v,B,N)}switch(N.m9){case 9:case 10:N.textEmphasis=1;break;case 11:N.textEmphasis=2;break;case 12:N.textEmphasis=3;break;case 13:N.textEmphasis=4;break;case 14:N.textEmphasis=5}return new uh(y,X,p,n,v.textContent||
"",B,N)},I8m=function(y,X,n,B,p){var f=g.cT(),G=f?g.PN("DIV"):g.PN("RUBY"),v=g.PN("SPAN");
v.textContent=y;G.appendChild(v);y=f?g.PN("DIV"):g.PN("RP");y.textContent=X;G.appendChild(y);X=f?g.PN("DIV"):g.PN("RT");X.textContent=n;G.appendChild(X);n=p.m9;if(n===10||n===11||n===12||n===13||n===14)if(g.nq(X,"text-emphasis-style","filled circle"),g.nq(X,"text-emphasis-color","currentcolor"),g.nq(X,"webkit-text-emphasis","filled circle"),p.m9===11||p.m9===13)g.nq(X,"webkit-text-emphasis-position","under left"),g.nq(X,"text-emphasis-position","under left");n=!0;if(p.m9===4||p.m9===7||p.m9===12||
p.m9===14)g.nq(G,"ruby-position","over"),g.nq(G,"-webkit-ruby-position","before");else if(p.m9===5||p.m9===6||p.m9===11||p.m9===13)g.nq(G,"ruby-position","under"),g.nq(G,"-webkit-ruby-position","after"),n=!1;p=f?g.PN("DIV"):g.PN("RP");p.textContent=B;G.appendChild(p);f&&(B=n,g.nq(G,{display:"inline-block",position:"relative"}),f=G.firstElementChild.nextElementSibling,g.nq(f,"display","none"),f=f.nextElementSibling,g.nq(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.nq(G.lastElementChild,"display","none"),B?(g.nq(G,"padding-top","0.6em"),g.nq(f,"top","0")):(g.nq(G,"padding-bottom","0.6em"),g.nq(f,"bottom","0")));return G},hRm=function(y){var X="_"+QV++;
return new KN(0,0x8000000000000,0,X,y)},rc=function(y,X){y=y.getAttribute(X);
if(y!=null)return Number(y)},Ml=function(y,X){y=y.getAttribute(X);
if(y!=null)return y==="1"},md=function(y,X){y=rc(y,X);
return y!==void 0?y:null},tR=function(y,X){y=y.getAttribute(X);
if(y!=null)return ea.test(y),y},Apm=function(y,X){var n={},B=X.getAttribute("ws");
Object.assign(n,B?y.U[B]:y.W);y=md(X,"mh");y!=null&&(n.X_=y);y=md(X,"ju");y!=null&&(n.textAlign=y);y=md(X,"pd");y!=null&&(n.V6=y);y=md(X,"sd");y!=null&&(n.oC=y);y=tR(X,"wfc");y!=null&&(n.windowColor=y);X=rc(X,"wfo");X!==void 0&&(n.windowOpacity=X/255);return n},wcj=function(y,X){var n={},B=X.getAttribute("wp");
B&&Object.assign(n,y.A[B]);y=md(X,"ap");y!=null&&(n.Ep=y);y=rc(X,"cc");y!=null&&(n.mk=y);y=rc(X,"ah");y!=null&&(n.s2=y);y=rc(X,"rc");y!=null&&(n.v2=y);X=rc(X,"av");X!=null&&(n.xg=X);return n},C9s=function(y,X,n,B){var p={};
Object.assign(p,wcj(y,X));Object.assign(p,Apm(y,X));B?g.Gw(p,y.W)?(B=y.V,p=y.W):B="_"+QV++:B=X.getAttribute("id")||"_"+QV++;y=rc(X,"t")+n;X=rc(X,"d")||0x8000000000000;if(p.V6===2||p.V6===3)n=p.v2,p.v2=p.mk,p.mk=n;return new KN(y,X,0,B,p)},IB=function(y){y=g.eF(Math.round(y),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-y.length)+y},ShL=function(y,X,n,B,p){B===0&&(B=0x8000000000000);
var f={};X.wpWinPosId&&Object.assign(f,y.W.get(X.wpWinPosId));X.wsWinStyleId&&Object.assign(f,y.V.get(X.wsWinStyleId));y=X.rcRowCount;y!==void 0&&(f.v2=y);X=X.ccColCount;X!==void 0&&(f.mk=X);if(f.V6===2||f.V6===3)X=f.v2,f.v2=f.mk,f.mk=X;return new KN(n,B,0,p,f)},k_=function(y){var X=y.byteOffset;
y.byteOffset+=1;return y.B.getUint8(X)},hR=function(y){var X=y.byteOffset;
y.byteOffset+=4;return y.B.getUint32(X)},dti=function(y){if(typeof y==="string")return!1;
y=new jnL(y,0);return a8I(y)},a8I=function(y){if(!(y.byteOffset<y.B.byteLength)||hR(y)!==1380139777)return!1;
y.version=k_(y);if(y.version>1)return!1;k_(y);k_(y);k_(y);return!0},YhG=function(y,X){if(!X)return"";
y.C&&y.Z.params.oC!==1&&(X*=-1);return`translate${y.C?"X":"Y"}(${X}px)`},qhV=function(y){y.wA=Array.from(y.element.getElementsByClassName("caption-visual-line"));
for(var X=y.Z.params.v2,n=0,B=0,p=y.wA.length-1;n<X&&p>-1;){var f=y.wA[p];B+=y.C?f.offsetWidth:f.offsetHeight;n++;p--}y.Z$=B;X=Math;n=X.max;isNaN(y.Fa)&&((B=y.B.mk)?(p=g.PN("SPAN"),g.kc(p,"\u2013".repeat(B)),g.nq(p,L9s(y,y.B.Qw)),y.V.appendChild(p),y.Fa=p.offsetWidth,y.V.removeChild(p)):y.Fa=0);B=y.V;y.Pb=n.call(X,y.Fa,y.hV,(y.C?B.offsetHeight:B.offsetWidth)+1)},F9L=function(y,X){qhV(y);
var n=y.wA.reduce((B,p)=>(y.C?p.offsetWidth:p.offsetHeight)+B,0);
n=y.Z$-n;if(n!==y.LI){let B=n>0&&y.LI===0,p=n<y.LI;X||isNaN(n)||B||!p||(g.sK(y.element,"ytp-rollup-mode"),y.G(y.element,"transitionend",y.C8));g.nq(y.V,"transform",YhG(y,n));y.LI=n}qhV(y)},XiH=function(y,X,n,B){var {formatId:p,
zs:f,startTimeMs:G,durationMs:v}=y.S(X),N={formatId:p,startTimeMs:G,durationMs:v,zj:f,Ky:f},J=yam(y.hA,N.startTimeMs),b=J>=0?y.hA[J]:null,l=b?b.startTimeMs+b.durationMs:0,L=N.startTimeMs+N.durationMs;!b||N.startTimeMs-l>y.W?y.hA.splice(J+1,0,N):(b.durationMs=Math.max(l,L)-b.startTimeMs,b.Ky=Math.max(b.Ky,N.Ky));B(y.hA);B=g.Qi(X);y=y.V;B=B.buffer.slice(B.byteOffset,B.byteLength+B.byteOffset);X=X.info.W;y.Bb?y.A==null?g.xD(y.logger,350058965,"Null loaded track meta data at captions data received"):
n.wI(B,y.A,X*1E3):g.xD(y.logger,350058965,"Null Representation at captions data received")},Bsc=function(y,X){y.D=(n,B)=>{if(y.X.N().experiments.Nt("html5_sabr_live_support_subfragmented_captions"))(y.B?y.B=y.B.V(n):(y.B=n,nWI(y.B)),y.B)?n.info.DL&&(gWc(y.B),XiH(y,y.B,X,B),y.B=null):g.xD(y.logger,350058965,"Empty slice");
else if(n.info.DL){var p=n;if(y.kg.length>0){for(p=y.kg.shift();y.kg.length>0;)p=p?.V(y.kg.shift());p=p?.V(n)}p?(nWI(p),gWc(p),XiH(y,p,X,B)):g.xD(y.logger,350058965,"Empty slice")}else y.kg.push(n)};
y.X.addEventListener("sabrCaptionsDataLoaded",y.D)},yam=function(y,X){y=g.X_(y,{startTimeMs:X},(n,B)=>n.startTimeMs-B.startTimeMs);
return y>=0?y:-y-2},nWI=function(y){try{var X=g.m_(y)*1E3}catch(n){X=y.info.segmentStartTime*1E3}X<0&&(X=y.info.segmentStartTime*1E3);
y.info.segmentStartTime=X/1E3;y.info.W=X/1E3},gWc=function(y){try{var X=g.hu(y)*1E3}catch(n){X=y.info.Z*1E3}X<0&&(X=y.info.Z*1E3);
y.info.Z=X/1E3;y.info.S=X/1E3},pib=function(y,X){if(!g.KC(y)||y.B!=null&&g.rW(X,y.B)&&y.B.B.rawcc!=null)return!1;
X=!!y.B&&y.B.isManifestless&&Object.values(y.B.B).some(n=>g.MP(n,"386"));
y=!!y.B&&!y.B.isManifestless&&g.od(y.B);return X||y},$Ec=function(y,X,n){var B=[];
for(let p in y.D.B){if(!y.D.B.hasOwnProperty(p))continue;let f=y.D.B[p];if(g.MP(f,n||null)){let G=f.info.captionTrack;G&&G.languageCode===X&&B.push(f)}}return B.length?B[0]:null},fHA=function(y,X){var n=[];
for(let p in y.D.B){if(!y.D.B.hasOwnProperty(p))continue;var B=y.D.B[p];if(g.MP(B,X||null)){let f=B.info.id,G=f,v=`.${f}`,N="",J="";if(B=B.info.captionTrack)f=B.languageCode,G=B.displayName,v=B.vssId,N=B.kind,J=B.id;n.push(new g.k$({id:p,languageCode:f,languageName:G,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:v,kind:N,captionId:J}))}}return n},vWi=function(y){var X=GsL.length;
if(y.byteLength<X)return!1;y=new Uint8Array(y,0,X);for(let n=0;n<X;n++)if(GsL[n]!==y[n])return!1;return!0},AR=function(y){y=y.split(":");
var X=0;for(let n of y)X=X*60+Number(n);return X*1E3},NsA=function(y,X,n,B){B=Object.assign({X_:0},B);
return new KN(y,X,n,"_"+QV++,B)},DEs=function(y,X,n,B,p,f,G,v,N){switch(G.tagName){case "b":v.bold=!0;
break;case "i":v.italic=!0;break;case "u":v.underline=!0}for(let b=0;b<G.childNodes.length;b++){var J=G.childNodes[b];if(J.nodeType===3)J=new uh(X,n,B,p.id,J.nodeValue,f||b>0,g.pr(v)?void 0:v),N.push(J),p.B.push(J);else{let l={};Object.assign(l,v);DEs(y,X,n,B,p,!0,J,l,N)}}},Tsc=function(y,X,n){if(typeof X==="string"||dti(X))return[{trackData:X,
zJ:n}];if(typeof X==="string"&&X.substring(0,6)==="WEBVTT"||typeof X!=="string"&&vWi(X))return[{trackData:X,zJ:n}];var B=new DataView(X);if(B.byteLength<=8||B.getUint32(4)!==1718909296)return[];var p=g.$9(B);if(y.K8&&p){var f=g.kJ(p),G=g.hO(p);p=p.segmentNumber;f&&p&&y.K8.sD(p,f,G)}y=g.g2(B,1835295092);if(!y||!y.length||!y[0].size)return[];f=[];for(G=0;G<y.length;G++)p=y[G],p=new Uint8Array(X,p.dataOffset,p.size-(p.dataOffset-p.offset)),p=g.Zm(p),f.push({trackData:p,zJ:n+G*1E3});oWI(B,f,n);return f=
f.filter(v=>!!v.trackData)},i1H=function(y,X,n){y.B||(y.B=new Z1m);
y=y.B.Z(X,n);Math.random()<.01&&g.$b(Error("Deprecated subtitles format in web player: WebVTT"));return y},oWI=function(y,X,n){var B=g.j9(y,0,1836476516),p=9E4;
B&&(p=g.YJ(B)||9E4);B=0;var f=g.g2(y,1836019558);for(let v=0;v<f.length;v++){var G=f[v];v<X.length&&(G=g.j9(y,G.dataOffset,1953653094))&&(G=g.j9(y,G.dataOffset,1952867444))&&(G=g.XB(G)/p*1E3,v===0&&(B=G),X[v].zJ=G-B+n||n*v*1E3)}},JaH=function(y){var X={};
if(y=g.wQ(y))X.lang=y,g.Ua7.test(y)&&(X.V6=1);return X},wc=function(y){return y.Z==="HLS"&&y.Hd?!0:y.YL&&y.Hd&&y.Z!=="LIVE"&&y.Z!=="SABR_LIVE"},b1A=function(y){return!y.W&&y.YL&&y.Bd&&(y.Z==="LIVE"||y.Z==="SABR_LIVE")},CN=function(y,X,n=!1){var B=y.Y.j("enable_player_captions_new_style_defaults")?O1H:lH7,p=B.Qw;
y.V={};Object.assign(y.V,B);y.V.Qw={};Object.assign(y.V.Qw,p);y.C={Qw:{}};var f=X.backgroundOverride?y.C:y.V,G=X.background||p.background;ea.test(G);f.Qw.background=G;f=X.colorOverride?y.C:y.V;G=X.color||p.color;ea.test(G);f.Qw.color=G;f=X.windowColorOverride?y.C:y.V;G=X.windowColor||B.windowColor;ea.test(G);f.windowColor=G;f=X.backgroundOpacityOverride?y.C:y.V;G=X.backgroundOpacity;G==null&&(G=p.backgroundOpacity);f.Qw.backgroundOpacity=G;f=X.fontSizeIncrementOverride?y.C:y.V;G=X.fontSizeIncrement;
G==null&&(G=p.fontSizeIncrement);f.Qw.fontSizeIncrement=G;G=X.fontStyleOverride?y.C:y.V;f=X.fontStyle;f==null&&(f=p.bold&&p.italic?3:p.bold?1:p.italic?2:0);G=G.Qw;switch(f){case 1:G.bold=!0;delete G.italic;break;case 2:delete G.bold;G.italic=!0;break;case 3:G.bold=!0;G.italic=!0;break;default:delete G.bold,delete G.italic}f=X.textOpacityOverride?y.C:y.V;G=X.textOpacity;G==null&&(G=p.textOpacity);f.Qw.textOpacity=G;f=X.windowOpacityOverride?y.C:y.V;G=X.windowOpacity;G==null&&(G=B.windowOpacity);f.windowOpacity=
G;B=X.charEdgeStyleOverride?y.C:y.V;f=X.charEdgeStyle;f==null&&(f=p.charEdgeStyle);B.Qw.charEdgeStyle=f;B=X.fontFamilyOverride?y.C:y.V;f=X.fontFamily;f==null&&(f=p.fontFamily);B.Qw.fontFamily=f;y.loaded&&y.Uy();n&&g.bM("yt-player-caption-display-settings",X,2592E3)},Sa=function(y,X,n){X&&!y.L?(X=hRm({V6:0,
lang:"en"}),y.L=[X,new uh(X.start,X.end-X.start,0,X.id,n??"Captions look like this")],y.player.sK(y.L)):!X&&y.L&&(UE1(y,y.L),y.L=null)},L4b=function(y){if(y.Y.j("enable_player_captions_persistence_state_machine")){var X=g.Oi("yt-player-caption-persistence");
if(X==null){let n=g.si().sy(65);if(n===!0)X=!1;else{let B=g.Gv(y.Y)?aB(y):VoV(y);B!=null?X=!!B:n===!1&&(X=!0)}X!==void 0&&dc(y,X)}return X}},aB=function(y){if(!y.X.isInline())return g.Oi("yt-player-sticky-caption")},VoV=function(y){if(!y.storage)return null;
try{var X=y.storage.get("module-enabled")}catch(n){y.storage.remove("module-enabled")}return X},Y_=function(y){if(y.Y.j("enable_player_captions_persistence_state_machine"))return L4b(y);
var X=void 0,n=g.si().sy(65);if(g.Gv(y.Y)&&n!=null){if(aB(y)!=null)return!1;X=!n}return X},EWb=function(y){if(y.Y.yP===1||y.videoData.Bt===1||g.LC(y.videoData,"yt:cc")==="alwayson")return!0;
if(y.videoData.captionTracks.length)var X=y.getAudioTrack().D;if(y.Y.j("enable_player_captions_persistence_state_machine")){var n=L4b(y);if(n!==void 0)return!!n}else if(y.Y.yP===2&&(g.Gv(y.Y)?n=aB(y):n=VoV(y),n!=null))return!!n;n=UA(y.player.getAudioTrack(),g.Gv(y.Y));var B=g.LC(y.videoData,"yt:cc");if(Y_(y)===void 0){if(n==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return B?B==="on":!0;if(n==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return B==="on"}else return B==="on";return X==="ON"||g.LC(y.videoData,
"yt:cc")==="on"},ql=function(y,X=!1){if(y.D&&!X||!y.videoData.captionTracks.length)return!1;
y=y.getAudioTrack();return!!y.B||y.D==="FORCED_ON"},sJ7=function(y){return y.Y.j("html5_honor_caption_availabilities_in_audio_track")&&y.Z!=="LIVE"&&y.Z!=="SABR_LIVE"},cac=function(y,X){if(y.D){var n=y.X.jL().Uh().textTracks,B=null;
y.Z==="HLS"?B=y.D.getId():B=y.D.toString();for(let f=0;f<n.length;f++){var p=n[f];p.id===B&&(X?p.mode!=="showing"&&(p.mode="showing",p=y.D,y.wD(p,!!p,Fh(y)?"g":y.A?"m":"s")):p.mode==="showing"&&(p.mode="disabled"))}}},Fh=function(y){var X=yr(y);
return!!X&&y.D===X},W4L=function(y,X){if(y.Z==="HLS")return!1;
g.PG(y.videoData)&&(X=!0);X||(X=y.Z==="TTS"?!1:y.Z==="INNERTUBE"?!1:!0);return X||y.Y.j("web_watch_disable_account_level_captions_settings")&&g.Gv(y.Y)?!0:!!g.si().sy(66)},yr=function(y){return y.U&&y.U.B},Xl=function(y,X){if(!y.B)return null;
if(y.U&&y.U.W)return y.U.W;X=W4L(y,X);X=y.B.B.B(X);var n=null;if(pcL(y.Y)){var B=y.X.isInline()?void 0:g.Oi("yt-player-caption-sticky-language");var p=[B,y.videoData.captionsLanguagePreference,y.Y.captionsLanguagePreference,g.LC(y.videoData,"yt:cc_default_lang")];let v=!1;for(let N=0;N<p.length;N++){let J=p[N];if(J){v=!0;for(var f=0;f<X.length;f++)if(g.wQ(X[f])===J)return X[f];for(f=0;f<X.length;f++)if(g.wQ(X[f]).split("-")[0]===J.split("-")[0])return X[f]}}if(v&&y.B&&(p=y.B.U,p.length))for(var G of p)if(G.languageCode===
B){n=G;break}}else for(G=[y.videoData.captionsLanguagePreference,y.Y.captionsLanguagePreference,g.LC(y.videoData,"yt:cc_default_lang")],B=0;B<G.length;B++)for(p=0;p<X.length;p++)if(g.wQ(X[p])===G[B])return X[p];G=null;y.U&&y.U.Z&&(G=y.U.Z);G||(G=X.find(v=>v.isDefault)||null);
G||(G=X[0]||yr(y));G&&n&&g.wQ(G).split("-")[0]!==n.languageCode.split("-")[0]&&(G=Bwj(G,n));return G},ps=function(y,X,n){y.loaded&&y.unload();
n!=null&&(y.A=n,y.A&&(y.Y.j("enable_player_captions_persistence_state_machine")?dc(y,!!X):g.Gv(y.Y)?ns(y,!!X):gj(y,!!X)));X!==null||ql(y,!0)||y.wD(X,!!X,y.A?"m":"s");y.D=X;ql(y)&&(y.D=yr(y));BW(y,y.D??void 0);y.load()},dc=function(y,X){y.Y.j("enable_player_captions_persistence_state_machine")&&g.bM("yt-player-caption-persistence",X,3122064E3)},ns=function(y,X){y.X.isInline()||g.bM("yt-player-sticky-caption",X,2592E3)},gj=function(y,X){if(y.storage)try{y.storage.set("module-enabled",X)}catch(n){}},
BW=function(y,X){y.Y.j("html5_modify_caption_vss_logging")&&(y.videoData.Fb=X)},zaH=function(y,X){var n=y.Pb[X.id];
n&&n.Z!==X&&(n.dispose(),delete y.Pb[X.id],n=null);n||(n=H1j(y,X))&&(y.Pb[X.id]=n)},RaV=function(y,X){var n=X.windowId;
y.Hb[n]||(y.Hb[n]=[]);y.Hb[n].push(X)},H1j=function(y,X){var n=xE1(y);
if(!n)return null;var B=y.D?g.wQ(y.D):null;B&&g.Ua7.test(B)&&(X.params.V6=1);var p=y.C8.getPlayerSize();B=p.height*y.Z$.height;p=p.width*y.Z$.width;y.Y.playerStyle!=="google-live"||y.V.isDefault||Object.assign(X.params,y.V);switch(X.params.X_!=null?X.params.X_:X.B.length>1?1:0){case 1:return new PzV(X,y.V,y.C,n.width,n.height,p,B,y.Y.experiments,y.l0.bind(y),y.X);case 2:return new uXA(X,y.V,y.C,n.width,n.height,p,B,y.Y.experiments,y.l0.bind(y),y.X);default:return new $o(X,y.V,y.C,n.width,n.height,
p,B,y.Y.experiments,y.l0.bind(y),y.X)}},xE1=function(y){var X=y.C8.getVideoContentRect(!0).height,n=y.C8.getVideoContentRect(!0).width;
if(!X||!n)return null;X*=y.Z$.height;n*=y.Z$.width;return{width:n,height:X}},UE1=function(y,X){y.player.p5(X);
for(let n of X)g.Cx(y.wA,n);OA(y.Fa)},QJ1=function(y,X){if(!y.B)return{};
if(X){g.pr(X)||y.qe(X.vss_id,"m");if(y.W&&y.Z!=="HLS"||!g.ls(X))return;if(g.pr(X)){ps(y,null,!0);return}let B;var n=y.B.B.B(!0);for(let p=0;p<n.length;p++){let f=n[p];f.languageCode!==X.languageCode||B&&(f.languageName!==X.languageName||(f.captionId||"")!==(X.captionId||"")||g.AB(f)!==X.displayName)||(B=X.translationLanguage?Bwj(f,X.translationLanguage):f)}y.jw(X.position);!B||B===y.D&&y.loaded||(X=g.bF(),n=g.wQ(B),X.length&&n===X[X.length-1]||(X.push(n),g.bM("yt-player-caption-language-preferences",
X)),pcL(y.Y)&&!y.X.isInline()&&g.bM("yt-player-caption-sticky-language",n,2592E3),ps(y,B,!0))}else return y.loaded&&y.D&&!Fh(y)?lh(y.D):{};return""};
g.zE.prototype.sD=g.nc(134,function(y,X,n){this.D.set(y,{gL:X,NZ:n})});
g.Rx.prototype.sD=g.nc(133,function(y,X,n){this.SO.sD(y,X,n)});
g.bp.prototype.A=g.nc(132,function(){this.mediaElement.A()});
g.T1.prototype.A=g.nc(131,function(){var y=g.lw(document,"track",void 0,this.B);for(let X=0;X<y.length;X++)g.r7(y[X])});
g.bp.prototype.LI=g.nc(130,function(){return this.mediaElement.LI()});
g.T1.prototype.LI=g.nc(129,function(){return!(!this.B.textTracks||!this.B.textTracks.addEventListener)});
g.bp.prototype.Hb=g.nc(128,function(){return this.mediaElement.Hb()});
g.T1.prototype.Hb=g.nc(127,function(){return!!this.B.textTracks});
g.bp.prototype.Z$=g.nc(126,function(y){this.mediaElement.Z$(y)});
g.T1.prototype.Z$=g.nc(125,function(y){for(let X=0;X<y.length;X++)this.B.appendChild(y[X])});
g.XZ.prototype.qe=g.nc(48,function(y,X){this.app.eO().qe(y,X)});
g.SX.prototype.qe=g.nc(47,function(y,X){this.J.qe(y,X)});
g.JA.prototype.qe=g.nc(46,function(y,X){y=[y,X];g.kn(this,g.An(this.provider),"cfi",y)});
g.lJ.prototype.qe=g.nc(45,function(y,X){this.qoe&&this.qoe.qe(y,X)});
g.Cj.prototype.qe=g.nc(44,function(y,X){this.ON.qe(y,X)});
g.cS.prototype.qe=g.nc(43,function(){});
g.wX.prototype.qe=g.nc(42,function(y,X){g.lO(this,37,[y,X])});
g.XZ.prototype.wD=g.nc(41,function(y,X,n){this.app.eO().wD(y,X,n)});
g.SX.prototype.wD=g.nc(40,function(y,X,n){this.J.wD(y,X,n)});
g.JA.prototype.wD=g.nc(39,function(y,X,n){if(this.hw!==y||this.G3!==X)X=X==="rawcc"?"":X,n=[y,X,this.hw,n],g.kn(this,g.An(this.provider),"cfs",n),this.hw=y,this.G3=X});
g.lJ.prototype.wD=g.nc(38,function(y,X,n){this.qoe&&this.qoe.wD(y,X,n)});
g.Cj.prototype.wD=g.nc(37,function(y,X,n){this.ON.wD(y,X,n)});
g.cS.prototype.wD=g.nc(36,function(){});
g.wX.prototype.wD=g.nc(35,function(y,X,n){g.lO(this,36,[y,X,n])});
g.q1.prototype.er=g.nc(11,function(){return this.K8});
g.uJ.prototype.er=g.nc(10,function(){return this.eO().KA()});
g.XZ.prototype.KA=g.nc(9,function(){return this.app.er()});
g.SX.prototype.KA=g.nc(8,function(){return this.J.KA()});
g.Cj.prototype.KA=g.nc(7,function(){return this.loader?.er()||null});
g.cS.prototype.KA=g.nc(6,function(){return null});
g.wX.prototype.KA=g.nc(5,function(){return null});
g.tq.prototype.bq=g.nc(3,function(y){return(y=this.Z(y))?y.B:0});
g.kh.prototype.bq=g.nc(2,function(){return 0});
var v6V=/#(.)(.)(.)/,GpA=/^#(?:[0-9a-f]{3}){1,2}$/i,K4H=class{constructor(){this.Z=[];this.D=[]}B(y){return y?this.D.concat(this.Z):this.D}},fs=class extends g.CX{constructor(y){super();this.nI=y;this.B=new K4H;this.Pb=new K4H;this.V=null;this.U=[];this.Z$=[]}S(){}W(){}Z(){}C(){return""}SO(){return!1}eE(y,X){if(this.nI.N().j("html5_dispatch_tracklist_loaded_event")){this.V&&(this.V.reject(),this.V=null);var n=[];this.nI.pI("trackListLoaded",this.B,n,X);this.nI.N().j("enable_po_decoration_of_forced_tracks")&&
this.nI.pI("trackListLoaded",this.Pb,n,X);n.length?(X=new g.c4,X.promise.then(y.eE,()=>{}),this.V=X,Promise.all(n).then(X.resolve,X.reject).finally(()=>{this.V=null})):y.eE()}else y.eE()}tw(){this.V&&(this.V.reject(),this.V=null);
this.Z();super.tw()}},raL={en:"English"},Mo0=class extends fs{constructor(y){super(y);this.D=new Set}W(y){var X=this.nI.jL();if(X&&X.Uh()){X=X.Uh().textTracks;for(let n of X)n.kind==="subtitles"&&!this.D.has(n.language)&&n.language&&(EA(this.B,new g.k$({languageCode:n.language,languageName:n.language,kind:n.kind,id:n.id,displayName:raL[n.label]||n.label,vss_id:`.${n.language}`})),this.D.add(n.language))}this.B.B().length>0&&y.eE()}},mE1=class extends fs{constructor(y,X,n){super(y);this.videoData=
X;this.audioTrack=n;this.D=null;this.A=!1;this.U=X.Tv;this.Z$=X.rT;this.A=g.PG(X)}S(y,X,n){this.Vo();X=this.C(y,X);var B=this.nI.N().j("html5_report_captions_ctmp_qoe"),p=(0,g.C)();this.Z();o61(this,X,{format:"RAW",onSuccess:f=>{this.D=null;if(B){var G=(f.responseText.length/1024).toFixed();let v=(0,g.C)();this.videoData.O("capresp",{ms:v-p,kb:G})}G=f.getResponseHeader&&f.getResponseHeader("Content-Length")?Number(f.getResponseHeader("Content-Length")):0;n.wI(f.responseText,y,void 0,void 0,G)},
onError:B?f=>{this.videoData.O("capfail",{status:f?.status??0})}:void 0,
withCredentials:!0})}W(y){if(this.audioTrack){for(let X of this.audioTrack.captionTracks)EA(this.B,X);this.audioTrack.B&&EA(this.Pb,this.audioTrack.B)}this.eE(y,this.videoData.videoId)}C(y,X){var n=y.KZ(),B={fmt:X};if(X==="srv3"||X==="3"||X==="json3")g.cT()?Object.assign(B,{xorb:2,xobt:1,xovt:1}):Object.assign(B,{xorb:2,xobt:3,xovt:3});y.translationLanguage&&(B.tlang=g.wQ(y));this.A&&(B.xosf="1");Object.assign(B,this.nI.N().B);return g.zC(n,B)}Z(){this.D&&this.D.abort()}},eaL=class{constructor(){this.segments=
[]}contains(y){y=g.X_(this.segments,y);return y>=0||y<0&&(-y-1)%2===1}length(){return this.segments.length/2}},tob=class extends g.CX{constructor(y,X,n,B,p,f){super();this.policy=y;this.player=X;this.la=n;this.A=B;this.V=p;this.Bb=f;this.W=new eaL;this.C=-1;this.D=this.Z=this.B=null;this.Z$=0;this.S=new g.b7(this.U,1E3,this);this.events=new g.hq(this);g.e(this,this.S);g.e(this,this.events);this.events.G(X,"SEEK_COMPLETE",this.L);this.L();this.U()}tw(){super.tw();this.D&&this.D.cancel()}L(){this.seekTo(this.player.getCurrentTime())}seekTo(y){y-=
this.player.JA();var X=this.B;this.B=g.x0(this.la.S(y).Mt);X!==this.B&&this.Bb&&this.Bb()}reset(){this.W=new eaL;this.C=-1;this.D&&(this.D.cancel(),this.D=null)}U(){this.Vo();var y;if(y=this.B!=null)y=this.B,y=y.la.W(y);if(y&&!this.D&&!(this.B&&this.B.segmentStartTime-this.player.getCurrentTime()>30)){y=this.B;y=y.la.YL(y);let p=y.Mt[0];if(this.player.getVideoData()?.enableServerStitchedDai){var X=this.player.KA();if(X){var n=p.la.info.id;let f=p.zs;var B=y.Mt[0].W;if(this.policy.Fa){if(X=g.DfV(X,
B,f,n,3))y.W=X}else if(n=X.Cv(B,f,n,3))if(B=2,X.rH.has(f)?B=0:g.tN(X,f)&&(B=1),X=B,X===0)n&&(y.B=new g.Mf(n));else if(X===2){this.S.start();ZlH(this)&&this.seekTo(this.player.getCurrentTime());return}}}p.la.index.ER(p.zs)?(this.W.contains(y.Mt[0].zs)||ilH(this,y),this.B=g.x0(y.Mt)):ZlH(this)&&this.seekTo(this.player.getCurrentTime())}this.S.start()}},IHH=class extends fs{constructor(y,X){super(X);this.D=y;this.X=X;this.A=null;this.L=!1;this.logger=new g.Rz("caps");this.Bb=g.rW(this.X,this.D)}S(y,
X,n){this.Z();X=JpL(this,y.getId());X||(X=y.languageCode,X=this.D.isManifestless?blb(this,X,"386"):blb(this,X));if(X){var B=(X.index.bq(X.index.W2())-X.index.getStartTime(X.index.W2()))*1E3,p=new g.dX0(this.X.N());this.A=new tob(p,this.X,X,(f,G)=>{n.wI(f,y,G,B)},this.Bb||g.tc(X.info),()=>{this.A&&this.A.reset();
this.L=!0})}}SO(){var y=this.L;
this.L=!1;return y}W(y){var X=this.X.N().j("html5_fallback_if_rawcc_missing");var n=this.D.B.rawcc!=null;if(!this.Bb||!n&&X)X=this.D.isManifestless?Ol0(this,"386"):Ol0(this);else{if(!n){g.xD(this.logger,386248249,"rawcc used but unavailable");return}X=[new g.k$({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.k$({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let B of X)EA(this.B,
B);y.eE()}Z(){this.A&&(this.A.dispose(),this.A=null)}C(){return""}},ksG=class extends fs{constructor(y,X,n,B,p,f){super(y);this.videoId=n;this.L=p;this.eventId=f;this.Bb={};this.D=null;y=B||g.WB(X).hl||"";y=y.split("_").join("-");this.A=g.zC(X,{hl:y})}S(y,X,n){this.Vo();X=this.C(y,X);this.Z();this.D=g.FT(X,{format:"RAW",onSuccess:B=>{this.D=null;var p=B.getResponseHeader&&B.getResponseHeader("Content-Length")?Number(B.getResponseHeader("Content-Length")):0;n.wI(B.responseText,y,void 0,void 0,p)},
withCredentials:!0})}W(y){var X=this.A,n={type:"list",tlangs:1,v:this.videoId,vssids:1};this.L&&(n.asrs=1);X=g.zC(X,n);this.Z();this.D=g.FT(X,{format:"RAW",onSuccess:B=>{this.D=null;if((B=B.responseXML)&&B.firstChild){var p=B.getElementsByTagName("track");for(var f=0;f<p.length;f++){var G=p[f],v=G.getAttribute("lang_code");let N=G.getAttribute("lang_translated"),J=G.getAttribute("name"),b=G.getAttribute("kind"),l=G.getAttribute("id"),L=G.getAttribute("lang_default")==="true",E=G.getAttribute("cantran")===
"true";G=G.getAttribute("vss_id");EA(this.B,new g.k$({languageCode:v,languageName:N,name:J,kind:b,id:l,is_servable:!0,is_translateable:E,vss_id:G,is_default:L}))}B=B.getElementsByTagName("target");p=B.length;for(f=0;f<p;f++)v={languageCode:B[f].getAttribute("lang_code"),languageName:B[f].getAttribute("lang_translated"),languageOriginal:B[f].getAttribute("lang_original"),id:B[f].getAttribute("id"),isDefault:B[f].getAttribute("lang_default")==="true"},this.Bb[v.languageCode]=v.languageName,this.U.push(v)}this.eE(y,
this.videoId)},
withCredentials:!0})}C(y,X){var n=this.A;X={v:this.videoId,type:"track",lang:y.languageCode,name:y.getName(),kind:y.kind,fmt:X};var B=this.nI.N();B.j("captions_url_add_ei")&&(X.ei=this.eventId);y.translationLanguage&&(X.tlang=g.wQ(y));Object.assign(X,B.B);return n=g.zC(n,X)}Z(){this.D&&this.D.abort()}},ea=/^#(?:[0-9a-f]{3}){1,2}$/i;var ha1=["left","right","center","justify"];var uh=class extends g.yO{constructor(y,X,n,B,p,f=!1,G=null){super(y,y+X,{priority:n,namespace:"captions"});this.windowId=B;this.text=p;this.append=f;this.B=G}toString(){return super.toString()}};var $o=class extends g.oc{constructor(y,X,n,B,p,f,G,v,N,J){var b=J.isInline()&&!0,l={};Object.assign(l,X);Object.assign(l,y.params);Object.assign(l,n);var L={};Object.assign(L,X.Qw);y.params.Qw&&Object.assign(L,y.params.Qw);Object.assign(L,n.Qw);b&&(l.windowOpacity=.6,L.backgroundOpacity=0);l.Qw=L;var E=l.V6===1,R=[{K:"span",gA:"captions-text",jO:{style:"word-wrap: normal; display: block;"}}],r=v.Nt("caption_edit_on_hover")&&J.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
r&&R.unshift({K:"button",gA:"caption-edit",jO:{tabindex:"0","aria-label":Nwm()},CI:[{K:"svg",jO:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},CI:[{K:"path",jO:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({K:"div",gA:"caption-window",jO:{id:`caption-window-${y.id}`,dir:E?"rtl":"ltr",tabindex:"0",lang:l.lang},CI:R});
this.experiments=v;this.U=[];this.YL=!1;this.Z=y;this.Hb=this.kL=null;this.Hq=f;this.Me=G;this.S=null;this.maxWidth=f*.96;this.maxHeight=G*.96;this.B=l;this.vZ=n;this.SO=X;this.V=this.dA("captions-text");y=this.V.style;this.hw=v.Nt("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in y||"WebkitBoxDecorationBreak"in y);this.Qo=l8c(B,p,f,G);this.cZ=N;r&&(this.A=this.dA("caption-edit"),this.G(this.A,"click",()=>{this.cZ()}));
this.type=0;this.l0=this.Qo*Ut0(L);this.UN=b;this.Bd=v.Nt("enable_centered_caption_for_tvfilm_video")&&J.getVideoData().isTvfilmVideo;this.Bb=J.N().ba().B.sy(g.yBm);B=new g.VE(this.element,!0);g.e(this,B);B.subscribe("dragstart",this.Cx,this);B.subscribe("dragmove",this.RK,this);B.subscribe("dragend",this.e9,this);this.NF=this.Hd=this.MF=this.u0=0;B="";this.B.windowOpacity&&(B=VV(this.B.windowColor),B="rgba("+B[0]+","+B[1]+","+B[2]+","+this.B.windowOpacity+")");p={"background-color":B,display:this.B.isVisible===
!1?"none":"","text-align":ha1[this.B.textAlign]};this.hw&&(p["border-radius"]=B?`${this.l0*.25}px`:"");(this.C=this.Z.params.V6===2||this.Z.params.V6===3)&&VTj(this,this.element);g.nq(this.element,p);b&&this.element.parentElement?.style.setProperty("--caption-window-color",B);switch(this.B.Ep){case 0:case 1:case 2:g.sK(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.sK(this.element,"ytp-caption-window-bottom")}}Cx(y,X){this.Hd=y;this.NF=X;var n=g.Td(this.element,this.element.parentElement);
this.u0=y-n.x;this.MF=X-n.y}RK(y,X){if(y!==this.Hd||X!==this.NF){g.EK(this.element,"ytp-dragging")||g.sK(this.element,"ytp-dragging");var n=g.bq(this.element);y=y-this.u0-.02*this.Hq;var B=X-this.MF-.02*this.Me,p=(y+n.width/2)/this.maxWidth*3;p=Math.floor(g.eF(p,0,2));var f=(B+n.height/2)/this.maxHeight*3;f=Math.floor(g.eF(f,0,2));X=p+f*3;y=(y+p/2*n.width)/this.maxWidth;y=g.eF(y,0,1)*100;n=(B+f/2*n.height)/this.maxHeight;n=g.eF(n,0,1)*100;this.Z.params.Ep=X;this.Z.params.xg=n;this.Z.params.s2=y;this.Z.params.isDefault=
!1;this.B.Ep=X;this.B.xg=n;this.B.s2=y;this.B.isDefault=!1;this.SO.Ep=X;this.SO.xg=n;this.SO.s2=y;this.SO.isDefault=!1;this.Ly()}}e9(){g.WO(this.element,"ytp-dragging")}Ly(){this.L(this.U)}L(y){var X=this.UN?0:Math.min(this.Eh(),this.maxWidth),n=this.G3(),B=this.UN;if(B){var p=getComputedStyle(this.V.parentNode);p=c_(p.borderLeftWidth)+c_(p.borderRightWidth)+c_(p.paddingLeft)+c_(p.paddingRight)}else p=0;var f=p;p="";this.Z.params.V6===3&&(p="rotate(180deg)");var G=B?`calc(96% - ${f}px)`:"96%";g.nq(this.element,
{top:0,left:0,right:"",bottom:"",width:X?`${X}px`:"",height:n?`${n}px`:"","max-width":G,"max-height":G,margin:"",transform:""});this.Uy(y);p={transform:p,top:"",left:"",width:X?`${X}px`:"",height:n?`${n}px`:"","max-width":"","max-height":""};G=this.B.Ep;var v=this.B.s2,N=this.B.xg;this.Bd&&G!=null&&(v=50,G=Math.floor(G/3)*3+1);v=v*.96+2;switch(G){case 0:case 3:case 6:(B=this.B.Qw.fontSizeIncrement)&&B>0&&this.B.V6!==2&&this.B.V6!==3&&(v=Math.max(v/(1+B*2),2));p.left=`${v}%`;break;case 1:case 4:case 7:p.left=
`${v}%`;v=0;this.Bb||(v=this.V.offsetWidth);X||v?(X=X||v+1,p.width=`${X}px`,p["margin-left"]=B?`${X/-2-f/2}px`:`${X/-2}px`):(this.Bb&&(p.width="max-content"),p.transform+=" translateX(-50%)");break;case 2:case 5:case 8:p.right=`${100-v}%`}B=N*.96+2;switch(G){case 0:case 1:case 2:p.top=`${B}%`;break;case 3:case 4:case 5:p.top=`${B}%`;B=0;this.Bb||(B=this.element.clientHeight);(n=n||B)?(p.height=`${n}px`,p["margin-top"]=`${n/-2}px`):p.transform+=" translateY(-50%)";break;case 6:case 7:case 8:p.bottom=
`${100-B}%`}g.nq(this.element,p);this.A&&(this.Bb?n=this.l0:(y=E6H(this,y),n=this.Bd?y>0?this.V.offsetHeight/y:0:this.V.offsetHeight/y),this.A.style.height=`${n}px`,this.A.style.width=`${n}px`,this.element.style.paddingLeft=`${n+5}px`,this.element.style.paddingRight=`${n+5}px`,this.Bb||(y=Number(this.element.style.marginLeft.replace("px",""))-n-5,n=Number(this.element.style.marginRight.replace("px",""))-n-5,this.element.style.marginLeft=`${y}px`,this.element.style.marginRight=`${n}px`))}Uy(y){if(this.type===
0&&this.Z.params.v2!==void 0&&this.experiments.Nt("web_enable_popon_asr_captions")){var X=y,n=this.Z.params.v2;if(X.length===0||n<=0)y=[];else{y=[];for(let p=X.length-1;p>=0;p--){var B=X[p];y.unshift(B);let f=E6H(this,y);if(f>n){y.shift();typeof B.text==="string"&&(X=B.text.split("\n"),n=f-n,X.length-n>0&&(n=X.slice(n),B=new uh(B.start,B.end-B.start,B.priority||0,B.windowId,n.join("\n"),B.append,B.B),y.unshift(B)));break}}}}for(B=0;B<y.length&&y[B]===this.U[B];B++);if(this.YL||this.U.length>B)B=0,
this.YL=!1,this.U=[],this.S=this.Hb=this.kL=null,g.QM(this.V);for(;B<y.length;B++)W9b(this,y[B])}Eh(){return 0}G3(){return 0}toString(){return super.toString()}};var wiI=class{constructor(){this.Z=this.time=this.mode=this.D=0;this.W=new AaI(this);this.V=new AaI(this);this.B=[];this.clear()}clear(){this.Z=this.time=this.mode=0;this.B=[];this.reset()}reset(){this.mode=0;this.W.reset(0);this.V.reset(1)}},Hlj=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],Czb=class{constructor(){this.type=0}set(y){this.type=y}get(){return this.type}},S3i=class{constructor(){this.state=this.QC=this.Ut=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}C2(){return this.state!==0}matches(y,X){return this.C2()&&y===this.Ut&&X===this.QC}},jJb=class{constructor(){this.timestamp=this.B=0}reset(){this.timestamp=
this.B=0}},G9=class{constructor(y){this.V=y;this.Z=[];this.B=this.D=this.row=0;this.style=new Czb;this.W=0;for(y=0;y<=15;y++){this.Z[y]=[];for(let X=0;X<=32;X++)this.Z[y][X]=new jJb}}updateTime(y){for(let X=1;X<=15;++X)for(let n=1;n<=32;++n)this.Z[X][n].timestamp=y}debugString(){var y="\n";for(let X=1;X<=15;++X){for(let n=1;n<=32;++n){let B=this.Z[X][n];y=B.B===0?y+"_":y+String.fromCharCode(B.B)}y+="\n"}return y}reset(y){for(let X=0;X<=15;X++)for(let n=0;n<=32;n++)this.Z[X][n].reset();this.W=y;this.B=
0;this.D=this.row=1}},uFI=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Qn7=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],K9L=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,
199,200,202,203,235,206,207,239,212,217,249,219,171,187],rpc=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],aHL=class{constructor(y){this.Z=y;this.V=0;this.style=new Czb;this.C=new G9(this.Z);this.S=new G9(this.Z);this.text=new G9(this.Z);this.D=this.C;this.W=this.S;this.B=this.D}reset(y,X){this.V=X;this.style.set(2);this.D=this.C;this.W=this.S;this.B=this.D;var n=(y<<2)+(X<<1);this.C.reset(n);this.S.reset(n);this.text.reset((y<<
2)+(X<<1)+1)}},AaI=class{constructor(y){this.B=y;this.V=0;this.Z=new aHL(this.B);this.C=new aHL(this.B);this.D=new S3i;this.W=this.Z}reset(y){this.V=y;this.D.clear();this.W=this.Z;this.Z.reset(y,0);this.C.reset(y,1)}};var dEI=class{W(){}};var vW=class extends g.CX{reset(){}};var KN=class extends g.yO{constructor(y,X,n,B,p){super(y,y+X,{priority:n,namespace:"captions"});this.id=B;this.params=p;this.B=[]}toString(){return super.toString()}},QV=0;var Y3j=class extends vW{constructor(y){super();this.W=y;this.pens={};this.A={};this.U={};this.V="_"+QV++;this.S={};this.D=this.B=null;this.C=!0}reset(){this.S={};this.D=this.B=null;this.C=!0}Z(y,X){y=y.firstChild;y.getAttribute("format");X=X||0;Number.isFinite(X);y=Array.from(y.childNodes);for(var n of y)if(n.nodeType===1)switch(n.tagName){case "head":var B=n;break;case "body":var p=n}if(B){B=Array.from(B.childNodes);for(var f of B)if(f.nodeType===1)switch(f.tagName){case "pen":n=f.getAttribute("id");
B=this.pens;y={};var G=f.getAttribute("p");G&&Object.assign(y,this.pens[G]);G=Ml(f,"b");G!=null&&(y.bold=G);G=Ml(f,"i");G!=null&&(y.italic=G);G=Ml(f,"u");G!=null&&(y.underline=G);G=md(f,"et");G!=null&&(y.charEdgeStyle=G);G=md(f,"of");G!=null&&(y.offset=G);G=tR(f,"bc");G!=null&&(y.background=G);G=tR(f,"ec");G!=null&&(y.lr=G);G=tR(f,"fc");G!=null&&(y.color=G);G=md(f,"fs");G!=null&&G!==0&&(y.fontFamily=G);G=rc(f,"sz");G!==void 0&&(y.fontSizeIncrement=G/100-1);G=rc(f,"bo");G!==void 0&&(y.backgroundOpacity=
G/255);G=rc(f,"fo");G!==void 0&&(y.textOpacity=G/255);G=md(f,"rb");G!=null&&G!==10&&G!==0&&(y.m9=G>10?G-1:G);G=md(f,"hg");G!=null&&(y.dJ=G);B[n]=y;break;case "ws":B=f.getAttribute("id");this.U[B]=Apm(this,f);break;case "wp":B=f.getAttribute("id"),this.A[B]=wcj(this,f)}}if(p){f=[];p=Array.from(p.childNodes);for(r of p)if(r.nodeType===1)switch(r.tagName){case "w":this.B=C9s(this,r,X,!1);(p=this.S[this.B.id])&&p.end>this.B.start&&(p.end=this.B.start);this.S[this.B.id]=this.B;f.push(this.B);break;case "p":var v=
r;y=X;p=[];B=v.getAttribute("w")||this.V;n=!!Ml(v,"a");y=(rc(v,"t")||0)+y;G=rc(v,"d")||5E3;n||(!this.C&&this.D&&this.D.windowId===B&&this.D.end>y&&(this.D.end=y),this.D&&this.D.text==="\n"&&(this.D.text=""));let k=n?6:5;var N=v.getAttribute("p");N=N?this.pens[N]:null;let I=Array.from(v.childNodes);I.length&&(this.C=v.getAttribute("d")!=null);for(v=0;v<I.length;v++){var J=I[v],b=void 0;v>0&&(n=!0);let A;J.nodeType===1&&(A=J);if(A&&A.tagName==="s"){if((J=(J=A.getAttribute("p"))?this.pens[J]:null)&&
J.m9&&(J.m9===1?(J=I.slice(v,v+4),J.length===4&&(b=kpG(y,G,B,n,k,J,this.pens),v+=3)):b=kpG(y,G,B,n,k,[A],this.pens)),!b){var l=A;b=y;J=G;var L=B,E=n;let d=l.textContent?l.textContent:"";var R=l.getAttribute("p");R=R?this.pens[R]:null;l=rc(l,"t")||0;b=new uh(b+l,J-l,k,L,d,E,R)}}else b=new uh(y,G,k,B,J.textContent||"",n,N);p.push(b);this.D=b}if(p.length>0){p[0].windowId===this.V&&(this.B=C9s(this,r,X,!0),f.push(this.B));for(let A of p)A.windowId=this.B.id,this.B.B.push(A),f.push(A)}}var r=f}else r=
[];return r}};var q3b=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),F4A=class extends vW{constructor(y){super();this.C=y;this.B=new Map;this.W=new Map;this.V=new Map;this.D=new Map}reset(){this.D.clear()}Z(y,X){y=JSON.parse(y);if(!y)return[];if(y.pens){var n=y.pens,B=0;for(var p of n){n={};var f=p.pParentId;f&&Object.assign(n,this.B.get(f));p.bAttr&&(n.bold=!0);p.iAttr&&(n.italic=!0);p.uAttr&&(n.underline=!0);f=p.ofOffset;f!=null&&(n.offset=f);p.szPenSize!==void 0&&(n.fontSizeIncrement=p.szPenSize/100-1);
f=p.etEdgeType;f!=null&&(n.charEdgeStyle=f);p.ecEdgeColor!==void 0&&(n.lr=IB(p.ecEdgeColor));f=p.fsFontStyle;f!=null&&f!==0&&(n.fontFamily=f);p.fcForeColor!==void 0&&(n.color=IB(p.fcForeColor));p.foForeAlpha!==void 0&&(n.textOpacity=p.foForeAlpha/255);p.bcBackColor!==void 0&&(n.background=IB(p.bcBackColor));p.boBackAlpha!==void 0&&(n.backgroundOpacity=p.boBackAlpha/255);(f=p.rbRuby)&&f!==10&&(n.m9=f>10?f-1:f,n.textEmphasis=q3b.get(n.m9));p.hgHorizGroup&&(n.dJ=p.hgHorizGroup);this.B.set(B++,n)}}if(y.wsWinStyles){B=
y.wsWinStyles;p=0;for(var G of B)B={},(n=G.wsParentId)?Object.assign(B,this.V.get(n)):Object.assign(B,this.C),G.mhModeHint!==void 0&&(B.X_=G.mhModeHint),G.juJustifCode!==void 0&&(B.textAlign=G.juJustifCode),G.pdPrintDir!==void 0&&(B.V6=G.pdPrintDir),G.sdScrollDir!==void 0&&(B.oC=G.sdScrollDir),G.wfcWinFillColor!==void 0&&(B.windowColor=IB(G.wfcWinFillColor)),G.wfoWinFillAlpha!==void 0&&(B.windowOpacity=G.wfoWinFillAlpha/255),this.V.set(p++,B)}if(y.wpWinPositions){p=y.wpWinPositions;G=0;for(var v of p)p=
{},(B=v.wpParentId)&&Object.assign(p,this.W.get(B)),v.ahHorPos!==void 0&&(p.s2=v.ahHorPos),v.apPoint!==void 0&&(p.Ep=v.apPoint),v.avVerPos!==void 0&&(p.xg=v.avVerPos),v.ccCols!==void 0&&(p.mk=v.ccCols),v.rcRows!==void 0&&(p.v2=v.rcRows),this.W.set(G++,p)}if(y.events){y=y.events;v=[];for(let q of y)if(G=(q.tStartMs||0)+X,p=q.dDurationMs||0,q.id)B=String(q.id),y=ShL(this,q,G,p,B),v.push(y),this.D.set(B,y);else{q.wWinId?B=q.wWinId.toString():(B="_"+QV++,y=ShL(this,q,G,p,B),v.push(y),this.D.set(B,y));
y=v;var N=q;p===0&&(p=5E3);n=this.D.get(B);let fc=(f=!!N.aAppend)?6:5,oj=N.segs,Lc=null;N.pPenId&&(Lc=this.B.get(N.pPenId));for(N=0;N<oj.length;N++){var J=oj[N],b=J.utf8;if(b){var l=J.tOffsetMs||0;let Rj=null;J.pPenId&&(Rj=this.B.get(J.pPenId));if((n.params.X_!=null?n.params.X_:n.B.length>1?1:0)===2&&f&&b==="\n")continue;J=null;var L=[],E;if(E=Rj&&Rj.m9===1)a:{E=oj;var R=N;if(R+3>=E.length||!E[R+1].pPenId||!E[R+2].pPenId||!E[R+3].pPenId){E=!1;break a}var r=E[R+1].pPenId;(r=this.B.get(r))&&r.m9&&r.m9===
2?(r=E[R+2].pPenId,r=this.B.get(r),!r||!r.m9||r.m9<3?E=!1:(r=E[R+3].pPenId,E=(r=this.B.get(r))&&r.m9&&r.m9===2?!0:!1)):E=!1}if(E)l=oj[N+1].utf8,J=oj[N+3].utf8,E=oj[N+2].utf8,R=this.B.get(oj[N+2].pPenId),b=I8m(b,l,E,J,R),J=new uh(G,p,fc,B,b,f,Rj),N+=3;else{if(b.indexOf("<")>-1){L=Rj;E=Lc;R=G;r=p;var k=l,I=fc,A=f;let jL=[];var d=sA(`<html>${b}</html>`);if(!d.getElementsByTagName("parsererror").length&&d.firstChild?.childNodes.length)for(let SL of d.firstChild.childNodes){d=SL.textContent?.replace(/\n/g,
"")??"";if(SL.nodeType===3&&(!d||d.match(/^ *$/)!=null))continue;let I2={};Object.assign(I2,L||E);switch(SL?.tagName){case "b":I2.bold=!0;break;case "i":I2.italic=!0;break;case "u":I2.underline=!0}jL.push(new uh(R+k,r-k,I,n.id,d,A,I2))}L=jL}L.length||(L=[new uh(G+l,p-l,fc,n.id,b,f,Rj||Lc)])}if(L.length)for(let jL of L)y.push(jL),n.B.push(jL);else J&&(y.push(J),n.B.push(J))}f=!0}}X=v}else X=[];return X}};var Tvs=class extends fs{constructor(y,X,n){super(y);this.videoData=X;this.audioTrack=n;this.U=X.Tv}S(y,X,n){f8j(this.videoData.videoId,y.vssId,n.wI)}W(y){if(this.audioTrack)for(let X of this.audioTrack.captionTracks)EA(this.B,X);y.eE()}};var PzV=class extends $o{constructor(y,X,n,B,p,f,G,v,N,J){super(y,X,n,B,p,f,G,v,N,J);this.type=1}Uy(y){var X=this.Z.B;super.Uy(y);for(y=y.length;y<X.length;y++){let p=X[y],f;if(B&&p.B===n)f=B;else{f={};Object.assign(f,p.B);Object.assign(f,ZnG);var n=p.B;var B=f}W9b(this,p,f)}}},ZnG={jD:!0};var jnL=class extends dEI{constructor(y,X){super();this.trackData=y;this.C=X;this.version=this.V=this.Z=this.byteOffset=0;this.D=[];this.B=new DataView(this.trackData)}W(y,X,n,B,p){if(n<B){let f="_"+QV++;n=n/1E3-this.C;B=B/1E3-this.C;y=new KN(n,B-n,5,f,{textAlign:0,Ep:0,s2:X*2.5,xg:y*5.33});p=new uh(n,B-n,5,f,p);this.D.push(y);this.D.push(p)}}},in1=class extends vW{constructor(y,X){super();this.D=y;this.W=X;this.track=this.W.languageName==="CC3"?4:0;this.B=new wiI;this.B.D=1<<this.track}Z(y){y=new jnL(y,
this.D);if(a8I(y)){for(;y.byteOffset<y.B.byteLength;)for(y.version===0?y.Z=hR(y)*(1E3/45):y.version===1&&(y.Z=hR(y)*4294967296+hR(y)),y.V=k_(y);y.V>0;y.V--){var X=k_(y);let n=k_(y),B=k_(y);X&4&&(X&3)===this.track&&(this.track===0||this.track===1)&&(X=this.B,X.B.push({time:y.Z,type:this.track,CQ:n,Fi:B,order:X.B.length}))}P9L(this.B,y);return y.D}return[]}reset(){this.B.clear()}};var uXA=class extends $o{constructor(y,X,n,B,p,f,G,v,N,J){super(y,X,n,B,p,f,G,v,N,J);this.type=2;this.wA=[];this.Pb=this.Z$=this.LI=0;this.Fa=NaN;this.hV=0;this.PZ=null;this.GT=new g.b7(this.C8,433,this);this.A&&(J.createClientVe(this.A,this,167342),this.G(this.A,"click",()=>{J.logClick(this.A)}),y=new g.VE(this.element,!0),g.e(this,y),y.subscribe("hoverstart",()=>{J.logVisibility(this.A,!0)},this));
g.sK(this.element,"ytp-caption-window-rollup");g.e(this,this.GT);g.nq(this.element,"overflow","hidden")}Ly(){var y=this.GT;y.stop();y.EG()}C8(){this.element.removeEventListener("transitionend",this.C8,!1);g.WO(this.element,"ytp-rollup-mode");this.L(this.PZ,!0)}G3(){return this.C?this.Pb:this.Z$}Eh(){return this.C?this.Z$:this.Pb}L(y,X){this.PZ=y;if(this.Z.params.v2){var n=0;for(let B=0;B<this.U.length&&n<y.length;B++)this.U[B]===y[n]&&n++;n>0&&n<y.length&&(y=this.U.concat(y.slice(n)));this.hV=this.Pb;
this.Z$=this.Pb=0;super.L(y);F9L(this,X)}super.L(y)}};var JfA=class{constructor(y,X,n,B){this.X=y;this.V=X;this.logger=n;this.p8=B;this.hA=[];this.B=null;this.Z=[];this.kg=[];this.D=null;y=g.uD(this.X.N().experiments,"html5_override_micro_discontinuities_threshold_ms");this.W=y>0?y:10}unload(){this.D!=null&&(this.X.removeEventListener("sabrCaptionsDataLoaded",this.D),this.D=null);this.hA=[];this.B=null;this.Z=[];this.X.pI("sabrCaptionsBufferedRangesUpdated",this.hA)}S(y){return{formatId:g.k9(y.info.la.info,this.p8),zs:y.info.zs+(this.p8?0:1),startTimeMs:y.info.W*
1E3,durationMs:y.info.S*1E3}}};var bnI=class extends fs{constructor(y,X){super(X);this.D=y;this.X=X;this.logger=new g.Rz("caps");this.A=this.Bb=null;this.L=new JfA(this.X,this,this.logger,this.D.p8)}S(y,X,n){this.Z();X=y.getId();X=X!=null&&X in this.D.B?this.D.B[X]:null;X||(X=y.languageCode,X=this.D.isManifestless?$Ec(this,X,"386"):$Ec(this,X));X&&(this.A=y,this.Bb=X,Bsc(this.L,n),this.X.pI("sabrCaptionsTrackChanged",g.k9(X.info,this.D.p8)))}W(y){var X=this.D.isManifestless?fHA(this,"386"):fHA(this);for(let n of X)EA(this.B,n);
y.eE()}Z(){this.A&&(this.A=this.Bb=null,this.L.unload(),this.X.pI("sabrCaptionsTrackChanged",null))}C(){return""}};var GsL="WEBVTT".split("").map(y=>y.charCodeAt(0)),Z1m=class extends vW{constructor(){super()}Z(y,X){y instanceof ArrayBuffer&&(y=g.Zm(new Uint8Array(y)));
var n=[];y=y.split(Onc);for(let R=1;R<y.length;R++){var B=y[R],p=X;if(B!==""&&!lyI.test(B)){var f=Ny.exec(B);if(f&&f.length>=4){var G=AR(f[1]),v=AR(f[2])-G;G+=p;var N=(f=f[3])?f.split(" "):[];f={};var J=null;var b="";var l=null,L="";for(let r of N){N=r.split(":");if(N.length!==2)continue;var E=N[1];switch(N[0]){case "line":N=E.split(",");N[0].endsWith("%")&&(J=N[0],f.xg=Number.parseInt(J,10),N.length===2&&(b=N[1].trim()));break;case "position":N=E.split(",");l=N[0];f.s2=Number.parseInt(l,10);N.length===
2&&(L=N[1].trim());break;case "align":switch(E){case "start":f.textAlign=0;break;case "middle":f.textAlign=2;break;case "end":f.textAlign=1}}}J||b||(b="end");if(!l)switch(f.textAlign){case 0:f.s2=0;break;case 1:f.s2=100;break;case 2:f.s2=50}if(f.textAlign!=null){J=0;switch(b){case "center":J+=3;break;case "end":J+=6;break;default:J+=0}switch(L){case "line-left":J+=0;break;case "center":J+=1;break;case "line-right":J+=2;break;default:switch(f.textAlign){case 0:J+=0;break;case 2:J+=1;break;case 1:J+=
2}}b=J<0||J>8?7:J;f.Ep=b}B=B.substring(Ny.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");L=f;f={};if(B.indexOf("<")<0&&B.indexOf("&")<0)p=NsA(G,v,5,L),G=new uh(G,v,5,p.id,B,!1,g.pr(f)?void 0:f),n.push(p),n.push(G),p.B.push(G);else for(b=B.split(U3c),b.length===1?(B=5,L=NsA(G,v,B,L)):(J=B=6,L=Object.assign({mk:32},L),L=new KN(G,v,J,"_"+QV++,L)),n.push(L),J=G,l=0;l<b.length;l++)if(N=b[l],l%2===0){E=sA(`<html>${N}</html>`);let r;E.getElementsByTagName("parsererror").length?(r=E.createElement("span"),
r.appendChild(E.createTextNode(N))):r=E.firstChild;DEs(this,J,v-(J-G),B,L,l>0,r,f,n)}else J=AR(N)+p}Ny.lastIndex=0}}return n}},lyI=/^NOTE/,Onc=/(?:\r\n|\r|\n){2,}/,Ny=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),U3c=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var VWs=class extends g.CX{constructor(y,X){super();this.X=y;this.Y=X;this.B=null;this.K8=this.X.KA();this.logger=new g.Rz("caps")}clear(){this.B&&this.B.dispose();this.B=null}reset(){this.B&&this.B.reset()}tw(){super.tw();this.clear()}};var lH7={windowColor:"#080808",windowOpacity:0,textAlign:2,Ep:7,s2:50,xg:100,isDefault:!0,Qw:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},O1H={windowColor:"#080808",windowOpacity:0,textAlign:0,Ep:7,s2:50,xg:100,isDefault:!0,Qw:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.Ke("captions",class extends g.Eb{constructor(y){super(y);this.X=y;this.wA=[];this.Pb={};this.Hb={};this.A=!1;this.Z="NONE";this.B=this.U=this.L=this.qt=this.Qo=null;this.sN={eE:()=>{this.eE()},
wI:(B,p,f,G,v=0)=>{var N=Number(this.videoData.N().ba().B.sy(g.Dbm)??0);v>0&&N>0&&this.videoData.lengthSeconds>0&&v/this.videoData.lengthSeconds>N?this.X.O("tts",{dropcap:v}):this.wI(B,p,f,G)}};
this.hw=this.D=null;this.Y=this.X.N();this.videoData=this.X.getVideoData();this.C8=this.X.e4();this.V={Qw:{}};this.C={Qw:{}};g.Ig(this.videoData)?this.Z="OFFLINE":g.qL1(this.videoData,this.X)?this.Z="HLS":pib(this.videoData,this.X)?this.Z="SABR_LIVE":g.FRG(this.videoData,this.X)?this.Z="LIVE":this.videoData.captionTracks.length?this.Z="INNERTUBE":this.videoData.MF&&(this.Z="TTS");this.YL=this.Y.controlsType==="3";this.LI=new VWs(this.X,this.Y);this.SO=new g.hq(this);this.S=new g.oc({K:"div",gA:"ytp-caption-window-container",
jO:{id:"ytp-caption-window-container"}});this.Z$={top:0,right:0,bottom:0,left:0,width:1,height:1};var X=null,n=g.qV("yt-html5-player-modules::subtitlesModuleData");n&&(X=new g.tX(n));this.storage=X;X=y.jL();this.Hd=!!X?.Hb();this.Bd=!!X?.LI();this.W=wc(this);this.Bb=b1A(this);g.e(this,this.LI);this.W?this.kL=this.Fa=null:(this.Fa=new g.ZZ(this.u0,void 0,this),g.e(this,this.Fa),this.kL=new g.b7(this.hV,2E3,this),g.e(this,this.kL));g.e(this,this.SO);g.zz(this.player,this.S.element,4);g.e(this,this.S);
this.W||this.SO.G(y,"resize",this.Uy);X=g.wx(this.Y)&&!g.gT()&&!this.X.isFullscreen();n=this.Y.ba().B.sy(g.uf0)&&g.gx(this.Y)&&g.Io;(this.NF=(X||n)&&!this.W&&!this.Bb)&&this.SO.G(y,X?"resize":"fullscreentoggled",this.UN);this.SO.G(y,"onPlaybackAudioChange",this.MF);this.SO.G(y,g.YV("captions"),B=>{this.onCueRangeEnter(B)});
this.SO.G(y,g.qQ("captions"),B=>{this.onCueRangeExit(B)});
CN(this,LN()||{});g.fV(this.player,"onCaptionsModuleAvailable");this.Z==="HLS"&&this.W&&(y=this.X.jL().Uh(),this.Bd&&this.SO.G(y.textTracks,"addtrack",this.G3))}tw(){if(this.W||this.Bb){let y=this.X.jL();y&&!y.Vo()&&y.A()}else Sa(this,!1);super.tw()}k8(){if(this.YL)return this.W||this.Bb;if(this.Z==="HLS")return this.W;var y=this.getAudioTrack();if(sJ7(this)){if(!y.captionTracks.length)return!1;if(!this.B)return!0}y=UA(y,g.Gv(this.Y));return y==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:y==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?
ql(this):Y_(this)||ql(this)?!0:EWb(this)}load(){super.load();this.U=this.getAudioTrack();if(this.B)this.D&&(this.LI.clear(),this.W?cac(this,!0):this.player.getPresentingPlayerType()!==3&&this.B.S(this.D,"json3",this.sN),this.Z!=="HLS"&&this.W||this.Bb||Fh(this)||g.fV(this.player,"captionschanged",lh(this.D)));else{if(this.Z==="OFFLINE")var y=new Tvs(this.player,this.videoData,this.getAudioTrack());else this.Z==="SABR_LIVE"?y=new bnI(this.videoData.B,this.player):this.Z==="HLS"?y=new Mo0(this.player):
this.Z==="LIVE"?y=new IHH(this.videoData.B,this.player):this.Z==="INNERTUBE"?y=new mE1(this.player,this.videoData,this.getAudioTrack()):(y=this.videoData,y=new ksG(this.player,this.videoData.MF,this.videoData.videoId,y.captionsLanguagePreference||y.D$.captionsLanguagePreference||g.LC(y,"yt:cc_default_lang")||y.D$.u0,this.videoData.vt,this.videoData.eventId));this.B=y;g.e(this,this.B);this.B.W(this.sN)}}unload(){this.W&&this.D?cac(this,!1):(this.kL&&this.kL.SY(),this.player.wK("captions"),this.wA=
[],this.B&&this.B.Z(),this.LI.clear(),this.L&&this.player.sK(this.L),this.Uy());super.unload();this.player.pR();g.fV(this.player,"captionschanged",{})}create(){this.k8()&&this.load();var y;a:{if(this.Y.j("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(y=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let X of y)if(X.kind==="asr"&&X.languageCode==="en"){y=
!0;break a}y=!1}y&&this.X.pI("showpromotooltip",this.S.element)}eE(){var y=UA(this.player.getAudioTrack(),g.Gv(this.Y));var X=y==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?Xl(this,this.A):y==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&ql(this)?yr(this):Y_(this)||this.A||EWb(this)?Xl(this,this.A):ql(this)?yr(this):null;if(this.Z!=="HLS"&&this.W||this.Bb){let n=this.B.B.B(!0);y=[];for(let B=0;B<n.length;B++){let p=n[B],f=g.PN("TRACK");f.setAttribute("kind","subtitles");f.setAttribute("label",g.AB(p));f.setAttribute("srclang",
g.wQ(p));f.setAttribute("id",p.toString());this.Bb||f.setAttribute("src",this.B.C(p,"vtt"));p===X&&f.setAttribute("default","1");y.push(f)}X=this.X.jL();X.Z$(y);y=X.Uh();this.Bd&&this.SO.G(y.textTracks,"change",this.BZ)}else!this.D&&X&&ps(this,X),g.fV(this.player,"onCaptionsTrackListChanged"),g.Gz(this.player,"onApiChange")}getTrackById(y){var X=this.B.B.B(!0);for(let n=0;n<X.length;n++)if(X[n].toString()===y)return X[n];return null}BZ(){var y=this.X.jL().Uh().textTracks,X=null;for(let n=0;n<y.length;n++)y[n].mode===
"showing"&&(X=this.getTrackById(y[n].id));(this.loaded?this.D:null)!==X&&ps(this,X,!0)}G3(){this.B?.W(this.sN)}aW(){!this.D&&this.W||this.unload()}wI(y,X,n,B){if(y){BW(this,this.D??void 0);this.B.SO()&&(this.wA=[],this.X.wK("captions"),OA(this.Fa),this.LI.reset());a:{var p=this.LI;B=B||0;n=Tsc(p,y,n||0);y=[];try{for(let I of n){let A=I.trackData,d=I.zJ,q=p.Y.j("safari_live_drm_captions_fix");if(typeof A!=="string"){n=y;var f=n.concat;if(q&&vWi(A))var G=i1H(p,A,d);else{var v=p,N=X,J=A,b=d,l=B;if(!dti(J))throw Error("Invalid binary caption track data");
v.B||(v.B=new in1(l,N));G=v.B.Z(J,b)}var L=f.call(n,G)}else{if(A.substring(0,6)==="WEBVTT")var E=y.concat(i1H(p,A,d));else{n=y;var R=n.concat;b:{N=p;v=X;if(A[0]==="{")try{N.B||(N.B=new F4A(JaH(v)));var r=N.B.Z(A,d);break b}catch(Lc){g.BY(Lc);r=[];break b}let fc=sA(A);if(!fc||!fc.firstChild){let Lc=Error("Invalid caption track data");Lc.params=A;throw Lc;}if(fc.firstChild.tagName==="timedtext"){if(Number(fc.firstChild.getAttribute("format"))===3){J=fc;N.B||(N.B=new Y3j(JaH(v)));r=N.B.Z(J,d);break b}let Lc=
Error("Unsupported subtitles format in web player (Format2)");Lc.params=A;throw Lc;}if(fc.firstChild.tagName==="transcript"){let Lc=Error("Unsupported subtitles format in web player (Format1)");Lc.params=A;throw Lc;}let oj=Error("Invalid caption track data");oj.params=A;throw oj;}E=R.call(n,r)}L=E}y=L}var k=y;break a}catch(I){g.xD(p.logger,187101178,`Captions parsing failed: ${I.message}. `);p.clear();k=[];break a}k=void 0}this.Y.j("html5_sabr_live_support_subfragmented_captions")&&this.B instanceof
bnI&&(X=this.B.L,p=[],k.length>0&&(p=k.slice(X.Z.length)),X.Z=!X.B||X.B.info.DL?[]:k,k=p);k.length>0&&(X=this.D,this.wD(X,!!X,Fh(this)?"g":this.A?"m":"s"));this.player.sK(k,void 0,this.Z==="LIVE"||this.Z==="SABR_LIVE");!this.A||this.Bb||Fh(this)||g.nM(this.Y)||g.F8(this.Y)||g.Cm(this.Y)||this.Y.A==="shortspage"||this.player.isInline()||(this.kL.SY(),k=hRm({Ep:0,s2:5,xg:5,v2:2,textAlign:0,V6:0,lang:"en"}),this.qt=[k],X=["Click "," for settings"],this.Qo||(p=new g.n3({K:"svg",jO:{height:"100%",version:"1.1",
viewBox:"0 0 36 36",width:"100%"},CI:[{K:"path",Lj:!0,jO:{d:"m 23.94,18.78 c .03,-0.25 .05,-0.51 .05,-0.78 0,-0.27 -0.02,-0.52 -0.05,-0.78 l 1.68,-1.32 c .15,-0.12 .19,-0.33 .09,-0.51 l -1.6,-2.76 c -0.09,-0.17 -0.31,-0.24 -0.48,-0.17 l -1.99,.8 c -0.41,-0.32 -0.86,-0.58 -1.35,-0.78 l -0.30,-2.12 c -0.02,-0.19 -0.19,-0.33 -0.39,-0.33 l -3.2,0 c -0.2,0 -0.36,.14 -0.39,.33 l -0.30,2.12 c -0.48,.2 -0.93,.47 -1.35,.78 l -1.99,-0.8 c -0.18,-0.07 -0.39,0 -0.48,.17 l -1.6,2.76 c -0.10,.17 -0.05,.39 .09,.51 l 1.68,1.32 c -0.03,.25 -0.05,.52 -0.05,.78 0,.26 .02,.52 .05,.78 l -1.68,1.32 c -0.15,.12 -0.19,.33 -0.09,.51 l 1.6,2.76 c .09,.17 .31,.24 .48,.17 l 1.99,-0.8 c .41,.32 .86,.58 1.35,.78 l .30,2.12 c .02,.19 .19,.33 .39,.33 l 3.2,0 c .2,0 .36,-0.14 .39,-0.33 l .30,-2.12 c .48,-0.2 .93,-0.47 1.35,-0.78 l 1.99,.8 c .18,.07 .39,0 .48,-0.17 l 1.6,-2.76 c .09,-0.17 .05,-0.39 -0.09,-0.51 l -1.68,-1.32 0,0 z m -5.94,2.01 c -1.54,0 -2.8,-1.25 -2.8,-2.8 0,-1.54 1.25,-2.8 2.8,-2.8 1.54,0 2.8,1.25 2.8,2.8 0,1.54 -1.25,2.8 -2.8,2.8 l 0,0 z",
fill:"#fff"}}]}),g.e(this,p),this.Qo=p.element),p=k.end-k.start,(L=g.AB(this.D))&&this.qt.push(new uh(k.start,p,0,k.id,L)),this.qt.push(new uh(k.start,p,0,k.id,X[0]),new uh(k.start,p,0,k.id,this.Qo,!0),new uh(k.start,p,0,k.id,X[1],!0)),this.player.sK(this.qt),g.OK(this.kL));!this.A||this.Bb||Fh(this)||(this.Y.j("enable_player_captions_persistence_state_machine")?dc(this,!0):g.Gv(this.Y)?ns(this,!0):gj(this,!0),this.U&&(this.U.W=this.D),this.player.pR());this.A=!1}}onCueRangeEnter(y){this.wA.push(y);
OA(this.Fa)}onCueRangeExit(y){g.Cx(this.wA,y);this.B instanceof IHH&&this.B.Bb&&this.player.p5([y]);OA(this.Fa)}getCaptionWindowContainerId(){return this.S.element.id}hV(){UE1(this,this.qt);this.qt=null}u0(){if(!this.NF||!this.W){this.Fa.stop();g.$c(this.Hb);this.wA.sort(g.dC);var y=this.wA;if(this.L){let X=g.Q4(y,function(n){return this.L.indexOf(n)===-1},this);
X.length&&(y=X)}for(let X of y)X instanceof KN?zaH(this,X):RaV(this,X);for(let [X,n]of Object.entries(this.Pb)){let B=X,p=n;this.Hb[B]?(p.element.parentNode||(p instanceof uXA||p instanceof PzV||g.aw(this.Pb,(f,G)=>{G!==B&&f.Z.params.Ep===p.Z.params.Ep&&f.Z.params.s2===p.Z.params.s2&&f.Z.params.xg===p.Z.params.xg&&(f.dispose(),delete this.Pb[G]);return G===B},this),this.S.element.appendChild(p.element)),p.L(this.Hb[B])):(p.dispose(),delete this.Pb[B])}}}uA(){CN(this,{},!0);
g.fV(this.player,"captionssettingschanged")}D0(){var y=this.Y.j("enable_player_captions_new_style_defaults")?O1H:lH7,X=y.Qw;y={background:X.background,backgroundOpacity:X.backgroundOpacity,charEdgeStyle:X.charEdgeStyle,color:X.color,fontFamily:X.fontFamily,fontSizeIncrement:X.fontSizeIncrement,fontStyle:X.bold&&X.italic?3:X.bold?1:X.italic?2:0,textOpacity:X.textOpacity,windowColor:y.windowColor,windowOpacity:y.windowOpacity};X=LN()||{};X.background!=null&&(y.background=X.background);X.backgroundOverride!=
null&&(y.backgroundOverride=X.backgroundOverride);X.backgroundOpacity!=null&&(y.backgroundOpacity=X.backgroundOpacity);X.backgroundOpacityOverride!=null&&(y.backgroundOpacityOverride=X.backgroundOpacityOverride);X.charEdgeStyle!=null&&(y.charEdgeStyle=X.charEdgeStyle);X.charEdgeStyleOverride!=null&&(y.charEdgeStyleOverride=X.charEdgeStyleOverride);X.color!=null&&(y.color=X.color);X.colorOverride!=null&&(y.colorOverride=X.colorOverride);X.fontFamily!=null&&(y.fontFamily=X.fontFamily);X.fontFamilyOverride!=
null&&(y.fontFamilyOverride=X.fontFamilyOverride);X.fontSizeIncrement!=null&&(y.fontSizeIncrement=X.fontSizeIncrement);X.fontSizeIncrementOverride!=null&&(y.fontSizeIncrementOverride=X.fontSizeIncrementOverride);X.fontStyle!=null&&(y.fontStyle=X.fontStyle);X.fontStyleOverride!=null&&(y.fontStyleOverride=X.fontStyleOverride);X.textOpacity!=null&&(y.textOpacity=X.textOpacity);X.textOpacityOverride!=null&&(y.textOpacityOverride=X.textOpacityOverride);X.windowColor!=null&&(y.windowColor=X.windowColor);
X.windowColorOverride!=null&&(y.windowColorOverride=X.windowColorOverride);X.windowOpacity!=null&&(y.windowOpacity=X.windowOpacity);X.windowOpacityOverride!=null&&(y.windowOpacityOverride=X.windowOpacityOverride);return y}hL(y,X){var n={};Object.assign(n,LN());Object.assign(n,y);CN(this,n,X);g.fV(this.player,"captionssettingschanged")}Uy(){!this.W&&this.loaded&&(g.C2(this.Pb,function(y,X){y.dispose();delete this.Pb[X]},this),this.u0())}KR(y,X){switch(y){case "fontSize":if(isNaN(X))break;
y=g.eF(X,-2,4);this.hL({fontSizeIncrement:y});return y;case "reload":X&&!this.W&&ps(this,this.D,!0);break;case "stickyLoading":X!==void 0&&this.Y.S&&(this.Y.j("enable_player_captions_persistence_state_machine")?dc(this,!(!X||!X.userInitiated)):g.Gv(this.Y)?ns(this,!!X):gj(this,!!X));break;case "track":return QJ1(this,X);case "tracklist":return this.B?g.Kx(this.B.B.B(!(!X||!X.includeAsr)),n=>lh(n)):[];
case "translationLanguages":return this.B?this.B.U.map(n=>Object.assign({},n)):[];
case "sampleSubtitles":this.W||X===void 0||Sa(this,!!X);break;case "sampleSubtitlesCustomized":this.W||Sa(this,!!X,X);break;case "recommendedTranslationLanguages":return g.bF();case "defaultTranslationSourceTrackIndices":return this.B?this.B.Z$:[]}}getOptions(){var y="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Y.S&&y.push("stickyLoading");return y}II(){var y=this.D;if(this.X.zk("captions")){if(this.Y.j("html5_modify_caption_vss_logging"))return(y=this.videoData.Fb??
null)?{cc:g.C0(y)}:{};if(y){let X=y.vssId;y.translationLanguage&&X&&(X=`t${X}.${g.wQ(y)}`);return{cc:X}}}return{}}Vt(y){this.isSubtitlesOn()?(this.Y.j("enable_player_captions_persistence_state_machine")&&y?dc(this,!1):g.Gv(this.Y)?ns(this,!1):gj(this,!1),BW(this),ps(this,null,!0)):this.El(y)}El(y){var X=Fh(this)||!this.D?Xl(this,!0):this.D;X&&this.qe(X.vssId,"m");this.isSubtitlesOn()||ps(this,X,this.Y.j("enable_player_captions_persistence_state_machine")?y:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.D&&!Fh(this)}MF(){var y=Fh(this);ql(this,y)?ps(this,this.getAudioTrack().B,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),sJ7(this)&&(this.A=!1,this.D=null,this.B&&(this.B.dispose(),this.B=null)),this.k8()&&(y?ps(this,Xl(this,!1),!1):this.load()))}LL(y){if(this.Y.experiments.Nt("web_enable_captions_set_target_container")&&y!==this.hw){var X=this.S.element;X.parentNode&&g.r7(X);(this.hw=y)?(this.hw.appendChild(X),X.style.position="absolute",X.style.bottom="0",X.style.left=
"0",X.style.width="100%",X.style.height="auto",X.style.top="auto"):(g.zz(this.player,X,4),X.style.position="absolute",X.style.bottom="auto",X.style.left="0",X.style.width="100%",X.style.height="100%",X.style.top="0");this.Uy()}}jw(y){y&&(this.Z$={top:y.top,right:y.right,bottom:y.bottom,left:y.left,width:1-y.left-y.right,height:1-y.top-y.bottom},this.S.element.style.top=`${this.Z$.top*100}%`,this.S.element.style.left=`${this.Z$.left*100}%`,this.S.element.style.width=`${this.Z$.width*100}%`,this.S.element.style.height=
`${this.Z$.height*100}%`,this.S.element.style.position="absolute",y=xE1(this))&&(this.S.element.style.width=`${y.width}px`,this.S.element.style.height=`${y.height}px`)}onVideoDataChange(y,X){y==="newdata"&&(this.videoData=X,this.loaded&&this.unload(),this.A=!1,this.D=null,this.B&&(this.B.dispose(),this.B=null,g.fV(this.player,"captionschanged",{})),this.k8()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}UN(){if(this.Y.ba().B.sy(g.uf0)){if(this.loaded&&this.unload(),this.YL=this.X.isFullscreen()||
this.Y.controlsType==="3",this.W=wc(this),this.Bb=b1A(this),this.W||this.Bb){var y=this.X.jL();y&&!y.Vo()&&y.A();this.eE()}}else(y=this.X.jL())&&!y.Vo()&&y.A(),this.X.isFullscreen()?(this.W=this.YL=!0,this.loaded&&this.eE()):(this.YL=this.Y.controlsType==="3",this.W=wc(this));ps(this,this.D)}l0(){var y=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;y&&g.$V(this.player,"innertubeCommand",y)}wD(y,X,n){var B=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,p="";y&&
(p=y.vssId,p=p.replace(B,""));var f="";y&&y.getId()&&(f=y.getId()||"");y&&y.getXtags()&&(y=y.getXtags(),y=y.replace(B,""),f=f.concat(`;${y}`));this.Z==="HLS"&&(f="");this.X.wD(X?p:"",X?f:"",n)}qe(y,X){y=(y||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");y.length>0&&this.X.qe(y,X)}});})(_yt_player);
