window.styleConfiguration = {
  metadata: {
    brandName: "KWSP",
    version: "1.0.0",
    language: "en",
    namespace: "brand-concierge"
},
  behavior: {
    multimodalCarousel: {
      cardClickAction: "openLink",
    },
    input: {
      enableVoiceInput: false,
      continuousVoiceMode: false,
      disableMultiline: true,
      showAiChatIcon: {
        icon: ""
      },
    },
    chat: {
      messageAlignment: "normal",
      messageWidth: "100%",
    },
    privacyNotice: {
      title: "Privacy Notice",
      text: "Your use of this automated chatbot constitutes your consent that the personal information you provide in the chat session can be collected, used, disclosed, and retained by KWSP and service providers acting on KWSP's behalf in accordance with the KWSP {Privacy Policy}. Please do not provide sensitive personal information (such as financial or health information) in the chatbot.",
      links: [
        {
          text: "Privacy Policy",
          url: "https://www.kwsp.gov.my/en/others/privacy-policy",
        },
      ],
    },
    chatTranscript: {
      enabled: true,
      maxSessions: 1,
      maxMessagesPerSession: 20,
      cleanupInterval: 24
    },
    meetingForm: {
      fieldsPerRow: 2,
      fieldLayoutRules: {
        textInputs: {
          allowTwoColumns: true,
          fieldTypes: ["string", "email", "tel", "number"],
        },
        dropdowns: {
          allowTwoColumns: false,
          fieldTypes: ["select"],
          identifyBy: "hasOptions",
        },
        checkboxes: {
          allowTwoColumns: false,
          fieldTypes: ["boolean", "checkbox"],
        },
      },
      title: {
        text: "Schedule meeting",
        alignment: "left",
      },
      subtitle: {
        text: "I'd be happy to help you schedule a meeting! Please fill out the form below, and we'll follow up with a calendar to confirm your day and time.",
        alignment: "left",
      },
      buttons: {
        submit: {
          text: "Schedule meeting",
          alignment: "left",
        },
        cancel: {
          text: "Cancel",
          alignment: "left",
        },
      },
    },
    calendarWidget: {
      title: {
        text: "Book a meeting",
        alignment: "left",
      },
      subtitle: {
        text: "Thanks! Here's a calendar where you can choose a time that works best for your schedule:",
        alignment: "left",
      },
      postTitle: {
        text: "Once confirmed, you'll receive a calendar invite with all the details. The specialist will already have this conversation context, so no need to repeat anything. Looking forward to connecting you with the right expert!",
        alignment: "left",
      },
      buttons: {
        confirm: {
          text: "Schedule a meeting",
          alignment: "left",
        },
        cancel: {
          text: "Cancel",
          alignment: "left",
        },
      },
    },
    productCard: { actionButtonSize: "S" },
  },
  disclaimer: {
    text: "This AI assistant is powered by Kwsp. Responses are generated based on your input and may not always be accurate or complete.",
    links: [
      {
        text: "Terms",
        url: "https://www.adobe.com/legal/licenses-terms/adobe-gen-ai-user-guidelines.html",
      },
    ],
  },
  text: {
    "welcome.heading": "Welcome to Kwsp",
    "welcome.subheading": "Your AI assistant for Kwsp. How can I help you today?",
    "input.placeholder": "Ask me anything about Kwsp...",
    "input.messageInput.aria": "Message input",
    "input.send.aria": "Send message",
    "input.aiChatIcon.tooltip": "Ask AI",
    "input.mic.aria": "Voice input",
    "card.aria.select": "Select example message",
    "carousel.prev.aria": "Previous cards",
    "carousel.next.aria": "Next cards",
    "scroll.bottom.aria": "Scroll to bottom",
    "error.network":
      "I'm sorry, I'm having trouble connecting to our services right now.",
    "loading.message": "Generating response from our knowledge base",
    "feedback.dialog.title.positive": "Your feedback is appreciated",
    "feedback.dialog.title.negative": "Your feedback is appreciated",
    "feedback.dialog.question.positive":
      "What went well? Select all that apply.",
    "feedback.dialog.question.negative":
      "What went wrong? Select all that apply.",
    "feedback.dialog.notes": "Notes",
    "feedback.dialog.submit": "Submit",
    "feedback.dialog.cancel": "Cancel",
    "feedback.dialog.notes.placeholder": "Additional notes (optional)",
    "feedback.toast.success": "Thank you for the feedback.",
    "feedback.thumbsUp.aria": "Thumbs up",
    "feedback.thumbsDown.aria": "Thumbs down",
  },
  arrays: {
    "welcome.examples": [
      {
        "text": "What can you help me with?",
        "systemPrompt": "What can you help me with?",
        "backgroundColor": "#507bff",
        "image": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPScyNDAnIGhlaWdodD0nMTYwJz48ZGVmcz48cGF0dGVybiBpZD0nZG90cycgd2lkdGg9JzE2JyBoZWlnaHQ9JzE2JyBwYXR0ZXJuVW5pdHM9J3VzZXJTcGFjZU9uVXNlJz48Y2lyY2xlIGN4PScyJyBjeT0nMicgcj0nMS41JyBmaWxsPScjZDlkOWQ5Jy8+PC9wYXR0ZXJuPjwvZGVmcz48cmVjdCB3aWR0aD0nMjQwJyBoZWlnaHQ9JzE2MCcgZmlsbD0nI2Y0ZjRmNCcvPjxyZWN0IHdpZHRoPScyNDAnIGhlaWdodD0nMTYwJyBmaWxsPSd1cmwoI2RvdHMpJy8+PC9zdmc+"
      },
      {
        "text": "Tell me about Kwsp",
        "systemPrompt": "Tell me about Kwsp.",
        "backgroundColor": "#6a8fff",
        "image": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPScyNDAnIGhlaWdodD0nMTYwJz48ZGVmcz48cGF0dGVybiBpZD0nZG90cycgd2lkdGg9JzE2JyBoZWlnaHQ9JzE2JyBwYXR0ZXJuVW5pdHM9J3VzZXJTcGFjZU9uVXNlJz48Y2lyY2xlIGN4PScyJyBjeT0nMicgcj0nMS41JyBmaWxsPScjZDlkOWQ5Jy8+PC9wYXR0ZXJuPjwvZGVmcz48cmVjdCB3aWR0aD0nMjQwJyBoZWlnaHQ9JzE2MCcgZmlsbD0nI2Y0ZjRmNCcvPjxyZWN0IHdpZHRoPScyNDAnIGhlaWdodD0nMTYwJyBmaWxsPSd1cmwoI2RvdHMpJy8+PC9zdmc+"
      },
      {
        "text": "How do I get started?",
        "systemPrompt": "How do I get started with Kwsp?",
        "backgroundColor": "#85a3ff",
        "image": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPScyNDAnIGhlaWdodD0nMTYwJz48ZGVmcz48cGF0dGVybiBpZD0nZG90cycgd2lkdGg9JzE2JyBoZWlnaHQ9JzE2JyBwYXR0ZXJuVW5pdHM9J3VzZXJTcGFjZU9uVXNlJz48Y2lyY2xlIGN4PScyJyBjeT0nMicgcj0nMS41JyBmaWxsPScjZDlkOWQ5Jy8+PC9wYXR0ZXJuPjwvZGVmcz48cmVjdCB3aWR0aD0nMjQwJyBoZWlnaHQ9JzE2MCcgZmlsbD0nI2Y0ZjRmNCcvPjxyZWN0IHdpZHRoPScyNDAnIGhlaWdodD0nMTYwJyBmaWxsPSd1cmwoI2RvdHMpJy8+PC9zdmc+"
      },
      {
        "text": "What are your key features?",
        "systemPrompt": "What are the key features of Kwsp?",
        "backgroundColor": "#9fb6ff",
        "image": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPScyNDAnIGhlaWdodD0nMTYwJz48ZGVmcz48cGF0dGVybiBpZD0nZG90cycgd2lkdGg9JzE2JyBoZWlnaHQ9JzE2JyBwYXR0ZXJuVW5pdHM9J3VzZXJTcGFjZU9uVXNlJz48Y2lyY2xlIGN4PScyJyBjeT0nMicgcj0nMS41JyBmaWxsPScjZDlkOWQ5Jy8+PC9wYXR0ZXJuPjwvZGVmcz48cmVjdCB3aWR0aD0nMjQwJyBoZWlnaHQ9JzE2MCcgZmlsbD0nI2Y0ZjRmNCcvPjxyZWN0IHdpZHRoPScyNDAnIGhlaWdodD0nMTYwJyBmaWxsPSd1cmwoI2RvdHMpJy8+PC9zdmc+"
      }
    ],
    "feedback.positive.options": [
      "Helpful and relevant recommendations",
      "Clear and easy to understand",
      "Friendly and conversational tone",
      "Visually appealing presentation",
      "Other",
    ],
    "feedback.negative.options": [
      "Not helpful or relevant",
      "Confusing or unclear",
      "Too formal or robotic",
      "Poor visual presentation",
      "Other",
    ],
  },
  assets: {
    icons: {
      company: "",
    },
  },
  theme: {
    "--welcome-input-order": "3",
    "--welcome-cards-order": "2",
    "--welcome-heading-size-desktop": "32px",
    "--welcome-heading-size-mobile": "28px",
    "--welcome-heading-weight": "700",
    "--welcome-heading-text-align": "center",
    "--welcome-subheading-size-desktop": "18px",
    "--welcome-subheading-size-mobile": "16px",
    "--welcome-subheading-text-align": "center",
    "--welcome-padding": "32px",
    "--prompt-suggestion-background": "#f3f3f3",
    "--prompt-suggestion-background-hover": "#e1e1e1",
    "--prompt-suggestion-text-color": "#292929",
    "--prompt-suggestion-border-color": "#dbdbdb",
    "--font-family": "'Adobe Clean', adobe-clean, 'Inter', 'Segoe UI', system-ui, sans-serif",
    "--color-primary": "#507bff",
    "--color-text": "#292929",
    "--line-height-body": "1.6",
    "--main-container-background": "linear-gradient(135deg, #ffcdb5 0%, #fff0e8 45%, #ede8ff 100%)",
    "--input-height": "52px",
    "--input-height-mobile": "48px",
    "--input-border-radius": "8px",
    "--input-border-radius-mobile": "8px",
    "--input-background": "#ffffff",
    "--input-outline-color": "#dbdbdb",
    "--input-outline-width": "1px",
    "--input-box-shadow": "0 2px 4px rgba(0,0,0,0.1)",
    "--input-focus-outline-width": "2px",
    "--input-focus-outline-color": "#507bff",
    "--input-font-size": "16px",
    "--input-font-weight": "400",
    "--input-text-color": "#292929",
    "--input-button-height": "40px",
    "--input-button-width": "40px",
    "--submit-button-fill-color": "#ffffff",
    "--submit-button-fill-color-disabled": "#CCCCCC",
    "--color-button-submit": "#507bff",
    "--color-button-submit-hover": "#3860fa",
    "--input-button-border-radius": "8px",
    "--button-disabled-background": "#F0F0F0",
    "--disclaimer-color": "#505050",
    "--disclaimer-font-size": "12px",
    "--disclaimer-font-weight": "400",
    "--message-user-background": "#507bff",
    "--message-user-text": "#ffffff",
    "--message-border-radius": "8px",
    "--message-padding": "16px",
    "--message-concierge-background": "#f3f3f3",
    "--message-concierge-text": "#000000",
    "--message-max-width": "100%",
    "--chat-interface-max-width": "768px",
    "--message-blocker-height": "48px",
    "--loading-message-background": null,
    "--loading-dot-background": null,
    "--color-text-muted": null,
    "--citations-text-font-weight": "700",
    "--citations-desktop-button-font-size": "14px",
    "--feedback-icon-btn-background": "#f3f3f3",
    "--feedback-icon-btn-hover-background": "#e1e1e1",
    "--feedback-icon-btn-size-desktop": "40px",
    "--feedback-container-gap": "16px",
    "--multimodal-card-box-shadow": "0 2px 12px rgba(0,0,0,0.08)",
    "--border-radius-card": "8px",
    "--button-height-s": "36px",
    "--button-primary-background": "#507bff",
    "--button-primary-text": "#ffffff",
    "--button-primary-hover": "#3860fa",
    "--button-secondary-border": "#dbdbdb",
    "--button-secondary-text": "#292929",
    "--button-secondary-hover": "#f3f3f3",
    "--color-button-secondary-hover-text": "#292929",
    "--privacy-notice-background": "#f3f3f3",
    "--privacy-notice-padding": "16px",
    "--privacy-notice-title-color": null,
    "--privacy-notice-text-color": null,
    "--privacy-notice-text-font-size": "14px",
    "--privacy-notice-title-font-size": "16px",
    "--message-concierge-link-decoration": "underline",
    "--color-secondary": "#e91e63",
    "--prompt-suggestion-button-background": "#f3f3f3",
    "--prompt-pill-background": "#507bff",
    "--button-primary-mobile-background": "#ff0000",
    "--button-primary-mobile-hover": "#cc0000",
    "--main-container-mobile-background": "linear-gradient(135deg, #ffcdb5 0%, #fff0e8 45%, #ede8ff 100%)",
    "--welcome-header-order": "1",
    "--welcome-heading-text-color": "#1a1a1a",
    "--welcome-subheading-text-color": "#505050",
    "--chat-container-background": "#f3f3f3",
    "--message-blocker-background": "#f3f3f3",
    "--message-concierge-border-width": "1px",
    "--message-concierge-link-color": "#507bff",
    "--prompt-suggestion-button-background-hover": "#e1e1e1",
    "--prompt-suggestion-button-text-color": "#292929",
    "--prompt-suggestion-button-border-radius": "16px",
    "--prompt-suggestion-button-padding": "8px 16px",
    "--prompt-suggestions-container-gap": "8px",
    "--prompt-suggestions-flex-direction": "row",
    "--prompt-suggestions-flex-wrap": "wrap",
    "--prompt-pill-text-color": "#ffffff",
    "--prompt-pill-border-color": "#3860fa",
    "--card-background": "#f3f3f3",
    "--card-border-radius": "8px",
    "--card-text-color": "#ffffff",
    "--card-text-font-size": "16px",
    "--card-text-padding": "16px"
  },
};
